In [1]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles available:")
print(os.listdir())

Current folder:
c:\Users\Manya\Downloads\track3_agritech_dataset_files

Files available:
['.venv', 'analyzing.ipynb', 'cleaned_mandi_master.csv', 'cleaned_price_and_msp.csv', 'cleaned_weather_sensors.csv', 'clean_track3_price_and_msp.py', 'clean_weather_sensors.py', 'join_price_mandi_master.py', 'mandi_cleaning.ipynb', 'price_and_msp_joined_mandi_master.csv', 'price_mandi_join_notebook.ipynb', 'price_msp_cleaning.ipynb', 'track3_dataset_notes.txt', 'track3_mandi_arrivals.csv', 'track3_mandi_master.csv', 'track3_price_and_msp.json', 'track3_transport_logistics.csv', 'track3_weather_sensors.xlsx', 'weather_by_date_and_district.csv']

In [2]:
import pandas as pd

# Load cleaned datasets
mandi = pd.read_csv("cleaned_mandi_master.csv")
price = pd.read_csv("cleaned_price_and_msp.csv")
weather = pd.read_csv("cleaned_weather_sensors.csv")

print("Mandi Master:", mandi.shape)
print("Price & MSP:", price.shape)
print("Weather:", weather.shape)

Mandi Master: (57, 6)
Price & MSP: (12000, 9)
Weather: (15000, 13)

In [3]:
print("MANDI COLUMNS:")
print(mandi.columns.tolist())

print("\nPRICE COLUMNS:")
print(price.columns.tolist())

print("\nWEATHER COLUMNS:")
print(weather.columns.tolist())

MANDI COLUMNS:
['Mandi_ID', 'Mandi_Name', 'District', 'State', 'Mandi_Type', 'Total_Area_Acres']

PRICE COLUMNS:
['record_id', 'date', 'mandi_id', 'district', 'crop_name', 'min_price', 'max_price', 'modal_price', 'msp']

WEATHER COLUMNS:
['sensor_id', 'is_sensor_unknown', 'timestamp', 'timestamp_tz', 'is_timestamp_missing', 'reported_temperature', 'reported_temperature_unit', 'temperature_c', 'reported_rainfall', 'reported_rainfall_unit', 'is_rainfall_negative_flag', 'rainfall_mm', 'humidity_percent']

In [4]:
print("PRICE DATA:")
display(price.head())

print("\nWEATHER DATA:")
display(weather.head())

print("\nMANDI DATA:")
display(mandi.head())

PRICE DATA:

,record_id,date,mandi_id,district,crop_name,min_price,max_price,modal_price,msp
0,PR001650,2026-07-26,MANDI005,Amritsar,Cotton,6850.99,7570.17,7210.58,6620.0
1,PR000246,2026-07-17,MANDI028,Fatehabad,Cotton,6944.79,7654.18,7299.00,NaN
2,PR010091,2026-01-09,MANDI011,Jalandhar,Rice,1857.00,2013.18,1935.06,2183.0
3,PR000982,2026-05-24,MANDI012,Ferozepur,Maize,1873.34,1986.00,1930.00,2090.0
4,PR001708,2026-08-18,MANDI013,Karnal,Cotton,5878.62,6574.28,6226.45,6620.0

WEATHER DATA:

,sensor_id,is_sensor_unknown,timestamp,timestamp_tz,is_timestamp_missing,reported_temperature,reported_temperature_unit,temperature_c,reported_rainfall,reported_rainfall_unit,is_rainfall_negative_flag,rainfall_mm,humidity_percent
0,SEN047,False,2026-08-28 00:00:00,unspecified,False,68.0,Fahrenheit,20.00,43.80,Millimeter,False,43.80,46.0
1,SEN034,False,2026-07-03 07:08:18,IST,False,85.3,Fahrenheit,29.61,1.88,Inch,False,47.75,55.0
2,SEN020,False,NaN,unspecified,True,18.9,Celsius,18.90,19.90,Millimeter,False,19.90,NaN
3,SEN035,False,2026-07-09 16:38:41,UTC,False,71.8,Fahrenheit,22.11,0.91,Inch,False,23.11,49.0
4,SEN048,False,2026-06-09 13:06:26,IST,False,39.8,Celsius,39.80,43.90,Millimeter,False,43.90,81.0

MANDI DATA:

,Mandi_ID,Mandi_Name,District,State,Mandi_Type,Total_Area_Acres
0,MANDI001,Hyderabad Mandi,Ludhiana,Punjab,PRIVATE,11.0
1,MANDI002,Solapur Mandi,Ludhiana,Unknown,APMC,37.0
2,MANDI003,Vijayawada Mandi,Ludhiana,Punjab,APMC,19.0
3,MANDI004,Khandwa Grain Market,Ludhiana,Punjab,APMC,15.0
4,MANDI005,Bhilwara Grain Market,Amritsar,Punjab,DIRECT,29.0

In [5]:
# Prepare Price & MSP data

price["date"] = pd.to_datetime(price["date"], errors="coerce")

price = price.rename(columns={
    "mandi_id": "Mandi_ID",
    "district": "District",
    "crop_name": "Crop",
    "modal_price": "Modal_Price",
    "msp": "MSP"
})

print("Price columns after preparation:")
print(price.columns.tolist())

print("\nDate range:")
print(price["date"].min(), "to", price["date"].max())

Price columns after preparation:
['record_id', 'date', 'Mandi_ID', 'District', 'Crop', 'min_price', 'max_price', 'Modal_Price', 'MSP']

Date range:
2026-01-01 00:00:00 to 2026-12-08 00:00:00

In [6]:
# Join Price data with Mandi Master

price_mandi = price.merge(
    mandi,
    on="Mandi_ID",
    how="left"
)

print("Joined dataset shape:", price_mandi.shape)

print("\nMissing Mandi information:")
print(price_mandi[["Mandi_Name", "State", "Mandi_Type"]].isna().sum())

print("\nSample:")
display(price_mandi.head())

Joined dataset shape: (12000, 14)

Missing Mandi information:
Mandi_Name    1235
State         1235
Mandi_Type    1235
dtype: int64

Sample:

,record_id,date,Mandi_ID,District_x,Crop,min_price,max_price,Modal_Price,MSP,Mandi_Name,District_y,State,Mandi_Type,Total_Area_Acres
0,PR001650,2026-07-26,MANDI005,Amritsar,Cotton,6850.99,7570.17,7210.58,6620.0,Bhilwara Grain Market,Amritsar,Punjab,DIRECT,29.0
1,PR000246,2026-07-17,MANDI028,Fatehabad,Cotton,6944.79,7654.18,7299.00,NaN,Machilipatnam APMC,Hisar,Haryana,APMC,33.0
2,PR010091,2026-01-09,MANDI011,Jalandhar,Rice,1857.00,2013.18,1935.06,2183.0,Arrah Mandi,Patiala,Punjab,APMC,34.0
3,PR000982,2026-05-24,MANDI012,Ferozepur,Maize,1873.34,1986.00,1930.00,2090.0,Gaya Grain Market,Patiala,Punjab,APMC,48.0
4,PR001708,2026-08-18,MANDI013,Karnal,Cotton,5878.62,6574.28,6226.45,6620.0,Aurangabad Market,Patiala,Punjab,PRIVATE,25.0

In [7]:
# Validate the Mandi Master join

print("Total price records:", len(price_mandi))

print("Records with matched Mandi:", price_mandi["Mandi_Name"].notna().sum())
print("Records without Mandi match:", price_mandi["Mandi_Name"].isna().sum())

print("\nUnique Mandi IDs in price data:", price_mandi["Mandi_ID"].nunique())
print("Unique Mandi IDs in master:", mandi["Mandi_ID"].nunique())

print("\nDuplicate Mandi IDs in master:")
print(mandi["Mandi_ID"].duplicated().sum())

Total price records: 12000
Records with matched Mandi: 10765
Records without Mandi match: 1235

Unique Mandi IDs in price data: 57
Unique Mandi IDs in master: 57

Duplicate Mandi IDs in master:
0

In [8]:
# Inspect weather data

print("Weather shape:", weather.shape)

print("\nWeather columns:")
print(weather.columns.tolist())

print("\nMissing values:")
print(weather.isna().sum())

print("\nFirst 5 rows:")
display(weather.head())

Weather shape: (15000, 13)

Weather columns:
['sensor_id', 'is_sensor_unknown', 'timestamp', 'timestamp_tz', 'is_timestamp_missing', 'reported_temperature', 'reported_temperature_unit', 'temperature_c', 'reported_rainfall', 'reported_rainfall_unit', 'is_rainfall_negative_flag', 'rainfall_mm', 'humidity_percent']

Missing values:
sensor_id                       0
is_sensor_unknown               0
timestamp                    1555
timestamp_tz                    0
is_timestamp_missing            0
reported_temperature            0
reported_temperature_unit       0
temperature_c                   0
reported_rainfall             791
reported_rainfall_unit        791
is_rainfall_negative_flag       0
rainfall_mm                   791
humidity_percent             1500
dtype: int64

First 5 rows:

,sensor_id,is_sensor_unknown,timestamp,timestamp_tz,is_timestamp_missing,reported_temperature,reported_temperature_unit,temperature_c,reported_rainfall,reported_rainfall_unit,is_rainfall_negative_flag,rainfall_mm,humidity_percent
0,SEN047,False,2026-08-28 00:00:00,unspecified,False,68.0,Fahrenheit,20.00,43.80,Millimeter,False,43.80,46.0
1,SEN034,False,2026-07-03 07:08:18,IST,False,85.3,Fahrenheit,29.61,1.88,Inch,False,47.75,55.0
2,SEN020,False,NaN,unspecified,True,18.9,Celsius,18.90,19.90,Millimeter,False,19.90,NaN
3,SEN035,False,2026-07-09 16:38:41,UTC,False,71.8,Fahrenheit,22.11,0.91,Inch,False,23.11,49.0
4,SEN048,False,2026-06-09 13:06:26,IST,False,39.8,Celsius,39.80,43.90,Millimeter,False,43.90,81.0

In [10]:
# Fix the weather Date column

weather["timestamp_ist"] = pd.to_datetime(
    weather["timestamp_ist"],
    errors="coerce"
)

weather["Date"] = weather["timestamp_ist"].dt.normalize()

print("Weather date range:")
print(weather["Date"].min(), "to", weather["Date"].max())

print("\nMissing dates:", weather["Date"].isna().sum())

display(weather[["timestamp", "timestamp_tz", "timestamp_ist", "Date"]].head())

Weather date range:
2026-01-01 00:00:00+05:30 to 2026-09-10 00:00:00+05:30

Missing dates: 1555

,timestamp,timestamp_tz,timestamp_ist,Date
0,2026-08-28 00:00:00,unspecified,2026-08-28 00:00:00+05:30,2026-08-28 00:00:00+05:30
1,2026-07-03 07:08:18,IST,2026-07-03 07:08:18+05:30,2026-07-03 00:00:00+05:30
2,NaN,unspecified,NaT,NaT
3,2026-07-09 16:38:41,UTC,2026-07-09 22:08:41+05:30,2026-07-09 00:00:00+05:30
4,2026-06-09 13:06:26,IST,2026-06-09 13:06:26+05:30,2026-06-09 00:00:00+05:30

In [11]:
weather_daily = pd.read_csv("weather_by_date_and_district.csv")

print("Shape:", weather_daily.shape)
print("\nColumns:")
print(weather_daily.columns.tolist())

display(weather_daily.head())

Shape: (1008, 10)

Columns:
['date', 'district', 'avg_temp_c', 'total_rain_mm', 'avg_humidity', 'sensor_count', 'District', 'State', 'Mandi_ID', 'Mandi_Type']

,date,district,avg_temp_c,total_rain_mm,avg_humidity,sensor_count,District,State,Mandi_ID,Mandi_Type
0,2026-01-01,Unknown,27.891607,1223.88,62.795455,36,Unknown,Punjab,MANDI017,PRIVATE
1,2026-01-01,Unknown,27.891607,1223.88,62.795455,36,Unknown,Haryana,MANDI032,PRIVATE
2,2026-01-01,Unknown,27.891607,1223.88,62.795455,36,Unknown,Haryana,MANDI039,APMC
3,2026-01-01,Unknown,27.891607,1223.88,62.795455,36,Unknown,Uttar Pradesh,MANDI046,PRIVATE
4,2026-01-02,Unknown,27.595806,1439.83,65.436364,37,Unknown,Punjab,MANDI017,PRIVATE

In [12]:
print("Weather sensor count:", weather["sensor_id"].nunique())
print("\nSensor IDs:")
print(sorted(weather["sensor_id"].unique()))

print("\nUnknown sensor rows:")
print(weather["is_sensor_unknown"].value_counts())

print("\nWeather columns:")
print(weather.columns.tolist())

Weather sensor count: 51

Sensor IDs:
['SEN001', 'SEN002', 'SEN003', 'SEN004', 'SEN005', 'SEN006', 'SEN007', 'SEN008', 'SEN009', 'SEN010', 'SEN011', 'SEN012', 'SEN013', 'SEN014', 'SEN015', 'SEN016', 'SEN017', 'SEN018', 'SEN019', 'SEN020', 'SEN021', 'SEN022', 'SEN023', 'SEN024', 'SEN025', 'SEN026', 'SEN027', 'SEN028', 'SEN029', 'SEN030', 'SEN031', 'SEN032', 'SEN033', 'SEN034', 'SEN035', 'SEN036', 'SEN037', 'SEN038', 'SEN039', 'SEN040', 'SEN041', 'SEN042', 'SEN043', 'SEN044', 'SEN045', 'SEN046', 'SEN047', 'SEN048', 'SEN049', 'SEN050', 'UNKNOWN']

Unknown sensor rows:
is_sensor_unknown
False    14285
True       715
Name: count, dtype: int64

Weather columns:
['sensor_id', 'is_sensor_unknown', 'timestamp', 'timestamp_tz', 'is_timestamp_missing', 'reported_temperature', 'reported_temperature_unit', 'temperature_c', 'reported_rainfall', 'reported_rainfall_unit', 'is_rainfall_negative_flag', 'rainfall_mm', 'humidity_percent', 'timestamp_ist', 'Date']

In [13]:
print("Unique dates:", weather_daily["date"].nunique())
print("Unique districts:", weather_daily["district"].nunique())
print("Unique Mandi IDs:", weather_daily["Mandi_ID"].nunique())

print("\nMandi IDs:")
print(sorted(weather_daily["Mandi_ID"].dropna().unique()))

print("\nDuplicate Date + Mandi_ID rows:")
print(
    weather_daily.duplicated(
        subset=["date", "Mandi_ID"]
    ).sum()
)

Unique dates: 252
Unique districts: 1
Unique Mandi IDs: 4

Mandi IDs:
['MANDI017', 'MANDI032', 'MANDI039', 'MANDI046']

Duplicate Date + Mandi_ID rows:
0

In [14]:
weather_daily = (
    weather.groupby("Date", as_index=False)
    .agg(
        Avg_Temperature_C=("temperature_c", "mean"),
        Total_Rainfall_mm=("rainfall_mm", "sum"),
        Avg_Humidity=("humidity_percent", "mean"),
        Sensor_Count=("sensor_id", "nunique")
    )
)

print("Weather daily shape:", weather_daily.shape)

print("\nColumns:")
print(weather_daily.columns.tolist())

display(weather_daily.head())

Weather daily shape: (253, 5)

Columns:
['Date', 'Avg_Temperature_C', 'Total_Rainfall_mm', 'Avg_Humidity', 'Sensor_Count']

,Date,Avg_Temperature_C,Total_Rainfall_mm,Avg_Humidity,Sensor_Count
0,2026-01-01 00:00:00+05:30,28.445849,1166.70,62.975610,36
1,2026-01-02 00:00:00+05:30,27.810667,1342.26,64.481481,37
2,2026-01-03 00:00:00+05:30,24.647097,1480.12,59.980769,35
3,2026-01-04 00:00:00+05:30,28.723091,1376.79,66.880000,35
4,2026-01-05 00:00:00+05:30,28.685000,1351.94,60.444444,30

In [15]:
price_daily = (
    price.groupby(
        ["date", "Mandi_ID", "Crop"],
        as_index=False
    )
    .agg(
        Min_Price=("min_price", "mean"),
        Max_Price=("max_price", "mean"),
        Modal_Price=("Modal_Price", "mean"),
        MSP=("MSP", "mean")
    )
)

print("Price daily shape:", price_daily.shape)

print("\nDuplicate Date + Mandi_ID + Crop rows:")
print(
    price_daily.duplicated(
        subset=["date", "Mandi_ID", "Crop"]
    ).sum()
)

display(price_daily.head())

Price daily shape: (10315, 7)

Duplicate Date + Mandi_ID + Crop rows:
0

        date  Mandi_ID    Crop  Min_Price  Max_Price  Modal_Price     MSP
0 2026-01-01  MANDI001  Cotton    6314.00    7889.00          NaN  6620.0
1 2026-01-01  MANDI003    Rice        NaN    2495.95      2248.00     NaN
2 2026-01-01  MANDI004   Narma    6673.83    7825.48      7249.66  6620.0
3 2026-01-01  MANDI004   Wheat    1997.69        NaN      2063.64  2275.0
4 2026-01-01  MANDI005  Cotton    6102.20    6418.63          NaN  6620.0

In [16]:
print("Crop names in price_daily:")
print(sorted(price_daily["Crop"].dropna().unique()))

print("\nNumber of unique crops:", price_daily["Crop"].nunique())

Crop names in price_daily:
['Chawal', 'Cotton', 'Ganne', 'Maize', 'Makki', 'Mustard', 'Narma', 'Rice', 'Sarso', 'Sugarcane', 'Wheat', 'चावल']

Number of unique crops: 12

In [17]:
crop_mapping = {
    "Chawal": "Rice",
    "चावल": "Rice",
    "Rice": "Rice",

    "Cotton": "Cotton",
    "Narma": "Cotton",

    "Ganne": "Sugarcane",
    "Sugarcane": "Sugarcane",

    "Maize": "Maize",
    "Makki": "Maize",

    "Mustard": "Mustard",
    "Sarso": "Mustard",

    "Wheat": "Wheat"
}

price_daily["Crop"] = price_daily["Crop"].map(crop_mapping)

print("Crop names after standardization:")
print(sorted(price_daily["Crop"].dropna().unique()))

print("\nNumber of unique crops:", price_daily["Crop"].nunique())

print("\nMissing crop names:", price_daily["Crop"].isna().sum())

Crop names after standardization:
['Cotton', 'Maize', 'Mustard', 'Rice', 'Sugarcane', 'Wheat']

Number of unique crops: 6

Missing crop names: 0

In [18]:
price_mandi_daily = price_daily.merge(
    mandi,
    on="Mandi_ID",
    how="left"
)

print("Price + Mandi daily shape:", price_mandi_daily.shape)

print("\nColumns:")
print(price_mandi_daily.columns.tolist())

print("\nMissing Mandi Master values:")
print(
    price_mandi_daily[
        ["Mandi_Name", "District", "State", "Mandi_Type"]
    ].isna().sum()
)

display(price_mandi_daily.head())

Price + Mandi daily shape: (10315, 12)

Columns:
['date', 'Mandi_ID', 'Crop', 'Min_Price', 'Max_Price', 'Modal_Price', 'MSP', 'Mandi_Name', 'District', 'State', 'Mandi_Type', 'Total_Area_Acres']

Missing Mandi Master values:
Mandi_Name    0
District      0
State         0
Mandi_Type    0
dtype: int64

,date,Mandi_ID,Crop,Min_Price,Max_Price,Modal_Price,MSP,Mandi_Name,District,State,Mandi_Type,Total_Area_Acres
0,2026-01-01,MANDI001,Cotton,6314.00,7889.00,NaN,6620.0,Hyderabad Mandi,Ludhiana,Punjab,PRIVATE,11.0
1,2026-01-01,MANDI003,Rice,NaN,2495.95,2248.00,NaN,Vijayawada Mandi,Ludhiana,Punjab,APMC,19.0
2,2026-01-01,MANDI004,Cotton,6673.83,7825.48,7249.66,6620.0,Khandwa Grain Market,Ludhiana,Punjab,APMC,15.0
3,2026-01-01,MANDI004,Wheat,1997.69,NaN,2063.64,2275.0,Khandwa Grain Market,Ludhiana,Punjab,APMC,15.0
4,2026-01-01,MANDI005,Cotton,6102.20,6418.63,NaN,6620.0,Bhilwara Grain Market,Amritsar,Punjab,DIRECT,29.0

In [19]:
weather["timestamp"] = pd.to_datetime(
    weather["timestamp"],
    errors="coerce"
)

def convert_to_ist(row):
    if pd.isna(row["timestamp"]):
        return pd.NaT

    ts = row["timestamp"]

    if row["timestamp_tz"] == "UTC":
        return ts.tz_localize("UTC").tz_convert("Asia/Kolkata")

    elif row["timestamp_tz"] == "IST":
        return ts.tz_localize("Asia/Kolkata")

    else:
        return ts.tz_localize("Asia/Kolkata")

weather["timestamp_ist"] = weather.apply(convert_to_ist, axis=1)

weather["Date"] = pd.to_datetime(
    weather["timestamp_ist"],
    errors="coerce"
).dt.normalize()

weather_daily = (
    weather.groupby("Date", as_index=False)
    .agg(
        Avg_Temperature_C=("temperature_c", "mean"),
        Total_Rainfall_mm=("rainfall_mm", "sum"),
        Avg_Humidity=("humidity_percent", "mean"),
        Sensor_Count=("sensor_id", "nunique")
    )
)

print("Weather daily shape:", weather_daily.shape)
print("\nDuplicate dates:", weather_daily["Date"].duplicated().sum())

display(weather_daily.head())

Weather daily shape: (253, 5)

Duplicate dates: 0

,Date,Avg_Temperature_C,Total_Rainfall_mm,Avg_Humidity,Sensor_Count
0,2026-01-01 00:00:00+05:30,28.445849,1166.70,62.975610,36
1,2026-01-02 00:00:00+05:30,27.810667,1342.26,64.481481,37
2,2026-01-03 00:00:00+05:30,24.647097,1480.12,59.980769,35
3,2026-01-04 00:00:00+05:30,28.723091,1376.79,66.880000,35
4,2026-01-05 00:00:00+05:30,28.685000,1351.94,60.444444,30

In [20]:
# Prepare dates for merging
price_mandi_daily["date"] = pd.to_datetime(
    price_mandi_daily["date"],
    errors="coerce"
).dt.normalize()

weather_daily["Date"] = pd.to_datetime(
    weather_daily["Date"],
    errors="coerce"
).dt.tz_localize(None)

# Merge weather data
final_data = price_mandi_daily.merge(
    weather_daily,
    left_on="date",
    right_on="Date",
    how="left"
)

# Remove duplicate date column
final_data = final_data.drop(columns=["Date"])

print("Final dataset shape:", final_data.shape)

print("\nColumns:")
print(final_data.columns.tolist())

print("\nWeather missing values after merge:")
print(
    final_data[
        ["Avg_Temperature_C", "Total_Rainfall_mm",
         "Avg_Humidity", "Sensor_Count"]
    ].isna().sum()
)

print("\nDuplicate Date + Mandi_ID + Crop rows:")
print(
    final_data.duplicated(
        subset=["date", "Mandi_ID", "Crop"]
    ).sum()
)

display(final_data.head())

Final dataset shape: (10315, 16)

Columns:
['date', 'Mandi_ID', 'Crop', 'Min_Price', 'Max_Price', 'Modal_Price', 'MSP', 'Mandi_Name', 'District', 'State', 'Mandi_Type', 'Total_Area_Acres', 'Avg_Temperature_C', 'Total_Rainfall_mm', 'Avg_Humidity', 'Sensor_Count']

Weather missing values after merge:
Avg_Temperature_C    167
Total_Rainfall_mm    167
Avg_Humidity         167
Sensor_Count         167
dtype: int64

Duplicate Date + Mandi_ID + Crop rows:
151

,date,Mandi_ID,Crop,Min_Price,Max_Price,Modal_Price,MSP,Mandi_Name,District,State,Mandi_Type,Total_Area_Acres,Avg_Temperature_C,Total_Rainfall_mm,Avg_Humidity,Sensor_Count
0,2026-01-01,MANDI001,Cotton,6314.00,7889.00,NaN,6620.0,Hyderabad Mandi,Ludhiana,Punjab,PRIVATE,11.0,28.445849,1166.7,62.97561,36.0
1,2026-01-01,MANDI003,Rice,NaN,2495.95,2248.00,NaN,Vijayawada Mandi,Ludhiana,Punjab,APMC,19.0,28.445849,1166.7,62.97561,36.0
2,2026-01-01,MANDI004,Cotton,6673.83,7825.48,7249.66,6620.0,Khandwa Grain Market,Ludhiana,Punjab,APMC,15.0,28.445849,1166.7,62.97561,36.0
3,2026-01-01,MANDI004,Wheat,1997.69,NaN,2063.64,2275.0,Khandwa Grain Market,Ludhiana,Punjab,APMC,15.0,28.445849,1166.7,62.97561,36.0
4,2026-01-01,MANDI005,Cotton,6102.20,6418.63,NaN,6620.0,Bhilwara Grain Market,Amritsar,Punjab,DIRECT,29.0,28.445849,1166.7,62.97561,36.0

In [21]:
duplicates = final_data[
    final_data.duplicated(
        subset=["date", "Mandi_ID", "Crop"],
        keep=False
    )
].sort_values(
    ["date", "Mandi_ID", "Crop"]
)

print("Duplicate rows found:", len(duplicates))
print("Duplicate groups:", duplicates[
    ["date", "Mandi_ID", "Crop"]
].drop_duplicates().shape[0])

display(
    duplicates[
        ["date", "Mandi_ID", "Crop",
         "Modal_Price", "MSP",
         "Avg_Temperature_C", "Total_Rainfall_mm"]
    ].head(20)
)

Duplicate rows found: 302
Duplicate groups: 151

,date,Mandi_ID,Crop,Modal_Price,MSP,Avg_Temperature_C,Total_Rainfall_mm
49,2026-01-02,MANDI008,Rice,2356.290,2183.0,27.810667,1342.26
50,2026-01-02,MANDI008,Rice,2087.260,2183.0,27.810667,1342.26
73,2026-01-02,MANDI037,Cotton,6518.270,6620.0,27.810667,1342.26
75,2026-01-02,MANDI037,Cotton,6253.280,6620.0,27.810667,1342.26
283,2026-01-08,MANDI032,Mustard,6311.000,5650.0,27.308571,1165.19
284,2026-01-08,MANDI032,Mustard,5470.550,5650.0,27.308571,1165.19
310,2026-01-09,MANDI027,Cotton,6399.440,6620.0,28.518727,1047.08
311,2026-01-09,MANDI027,Cotton,7033.510,6620.0,28.518727,1047.08
315,2026-01-09,MANDI032,Rice,2485.320,NaN,28.518727,1047.08
316,2026-01-09,MANDI032,Rice,2220.930,2183.0,28.518727,1047.08
443,2026-01-13,MANDI009,Cotton,7480.000,NaN,26.730400,1224.62
444,2026-01-13,MANDI009,Cotton,6898.750,6620.0,26.730400,1224.62
491,2026-01-14,MANDI009,Rice,2275.000,2183.0,26.127736,1251.41
492,2026-01-14,MANDI009,Rice,2054.110,2183.0,26.127736,1251.41
622,2026-01-17,MANDI025,Rice,2276.440,2183.0,29.820196,1367.73
623,2026-01-17,MANDI025,Rice,2156.400,2183.0,29.820196,1367.73
688,2026-01-18,MANDI049,Maize,2145.525,2090.0,28.178409,1183.27
689,2026-01-18,MANDI049,Maize,2119.280,2090.0,28.178409,1183.27
750,2026-01-20,MANDI012,Maize,1914.830,NaN,27.926604,1207.03
751,2026-01-20,MANDI012,Maize,2252.000,2090.0,27.926604,1207.03

In [22]:
# Remove duplicate Date + Mandi_ID + Crop combinations
final_data = (
    final_data
    .groupby(
        ["date", "Mandi_ID", "Crop"],
        as_index=False
    )
    .agg({
        "Min_Price": "mean",
        "Max_Price": "mean",
        "Modal_Price": "mean",
        "MSP": "mean",
        "Mandi_Name": "first",
        "District": "first",
        "State": "first",
        "Mandi_Type": "first",
        "Total_Area_Acres": "first",
        "Avg_Temperature_C": "first",
        "Total_Rainfall_mm": "first",
        "Avg_Humidity": "first",
        "Sensor_Count": "first"
    })
)

print("Final dataset shape:", final_data.shape)

print("\nDuplicate Date + Mandi_ID + Crop rows:")
print(
    final_data.duplicated(
        subset=["date", "Mandi_ID", "Crop"]
    ).sum()
)

display(final_data.head())

Final dataset shape: (10164, 16)

Duplicate Date + Mandi_ID + Crop rows:
0

,date,Mandi_ID,Crop,Min_Price,Max_Price,Modal_Price,MSP,Mandi_Name,District,State,Mandi_Type,Total_Area_Acres,Avg_Temperature_C,Total_Rainfall_mm,Avg_Humidity,Sensor_Count
0,2026-01-01,MANDI001,Cotton,6314.00,7889.00,NaN,6620.0,Hyderabad Mandi,Ludhiana,Punjab,PRIVATE,11.0,28.445849,1166.7,62.97561,36.0
1,2026-01-01,MANDI003,Rice,NaN,2495.95,2248.00,NaN,Vijayawada Mandi,Ludhiana,Punjab,APMC,19.0,28.445849,1166.7,62.97561,36.0
2,2026-01-01,MANDI004,Cotton,6673.83,7825.48,7249.66,6620.0,Khandwa Grain Market,Ludhiana,Punjab,APMC,15.0,28.445849,1166.7,62.97561,36.0
3,2026-01-01,MANDI004,Wheat,1997.69,NaN,2063.64,2275.0,Khandwa Grain Market,Ludhiana,Punjab,APMC,15.0,28.445849,1166.7,62.97561,36.0
4,2026-01-01,MANDI005,Cotton,6102.20,6418.63,NaN,6620.0,Bhilwara Grain Market,Amritsar,Punjab,DIRECT,29.0,28.445849,1166.7,62.97561,36.0

In [23]:
print("Missing values in final dataset:")
print(final_data.isna().sum())

Missing values in final dataset:
date                    0
Mandi_ID                0
Crop                    0
Min_Price             470
Max_Price             476
Modal_Price           502
MSP                  1943
Mandi_Name              0
District                0
State                   0
Mandi_Type              0
Total_Area_Acres        0
Avg_Temperature_C     167
Total_Rainfall_mm     167
Avg_Humidity          167
Sensor_Count          167
dtype: int64

In [24]:
print("Missing MSP by crop:")

print(
    final_data.groupby("Crop")["MSP"]
    .apply(lambda x: x.isna().sum())
    .sort_values(ascending=False)
)

print("\nTotal rows by crop:")

print(
    final_data["Crop"]
    .value_counts()
)

Missing MSP by crop:
Crop
Sugarcane    347
Wheat        328
Mustard      326
Maize        321
Cotton       320
Rice         301
Name: MSP, dtype: int64

Total rows by crop:
Crop
Maize        1718
Mustard      1711
Sugarcane    1702
Cotton       1699
Wheat        1683
Rice         1651
Name: count, dtype: int64

In [25]:
price_columns = [
    "Min_Price",
    "Max_Price",
    "Modal_Price",
    "MSP"
]

print("Zero or negative values:")

for col in price_columns:
    count = (final_data[col] <= 0).sum()
    print(f"{col}: {count}")

Zero or negative values:
Min_Price: 0
Max_Price: 0
Modal_Price: 0
MSP: 0

In [26]:
# Identify price crash instances
final_data["Price_Crash"] = (
    final_data["Modal_Price"] < final_data["MSP"]
)

print("Total price crash instances:")
print(final_data["Price_Crash"].sum())

print("\nPrice crash rate:")
print(
    round(final_data["Price_Crash"].mean() * 100, 2),
    "%"
)

Total price crash instances:
3079

Price crash rate:
30.29 %

In [27]:
crash_by_crop = (
    final_data.groupby("Crop")["Price_Crash"]
    .agg(
        Crash_Instances="sum",
        Total_Records="count"
    )
)

crash_by_crop["Crash_Rate_%"] = (
    crash_by_crop["Crash_Instances"]
    / crash_by_crop["Total_Records"]
    * 100
)

crash_by_crop = crash_by_crop.sort_values(
    "Crash_Rate_%",
    ascending=False
)

print(crash_by_crop)

           Crash_Instances  Total_Records  Crash_Rate_%
Crop
Wheat                  542           1683     32.204397
Maize                  539           1718     31.373690
Rice                   508           1651     30.769231
Cotton                 508           1699     29.899941
Mustard                501           1711     29.281122
Sugarcane              481           1702     28.260870

In [28]:
price_comparison = (
    final_data
    .groupby("Crop")
    .agg(
        Avg_Modal_Price=("Modal_Price", "mean"),
        Avg_MSP=("MSP", "mean")
    )
)

price_comparison["Price_Gap"] = (
    price_comparison["Avg_Modal_Price"]
    - price_comparison["Avg_MSP"]
)

price_comparison["Price_Gap_%"] = (
    price_comparison["Price_Gap"]
    / price_comparison["Avg_MSP"]
    * 100
)

print(price_comparison.round(2))

           Avg_Modal_Price  Avg_MSP  Price_Gap  Price_Gap_%
Crop
Cotton             6764.91   6620.0     144.91         2.19
Maize              2134.17   2090.0      44.17         2.11
Mustard            5786.79   5650.0     136.79         2.42
Rice               2230.77   2183.0      47.77         2.19
Sugarcane          3575.10   3500.0      75.10         2.15
Wheat              2317.35   2275.0      42.35         1.86

In [29]:
arrivals = pd.read_csv("cleaned_mandi_arrivals.csv")

In [30]:
print(arrivals.shape)
print(arrivals.columns.tolist())

(25000, 1)
['Arrival_ID\tDate\tMandi_ID\tCrop_Name\tVariety\tArrival_Quantity_Quintals\tArrival_Quantity_Mt\tArrival_Quantity_Kg\tReported_Quantity\tReported_Unit\tFarmer_Count\tIs_Arrival_ID_Imputed\tIs_Quantity_Negative_Flag']

In [31]:
arrivals = pd.read_csv("cleaned_mandi_arrivals.csv", sep="\t")

print(arrivals.shape)
print(arrivals.columns.tolist())

(25000, 13)
['Arrival_ID', 'Date', 'Mandi_ID', 'Crop_Name', 'Variety', 'Arrival_Quantity_Quintals', 'Arrival_Quantity_Mt', 'Arrival_Quantity_Kg', 'Reported_Quantity', 'Reported_Unit', 'Farmer_Count', 'Is_Arrival_ID_Imputed', 'Is_Quantity_Negative_Flag']

In [32]:
print("Negative arrival quantities:")
print((arrivals["Arrival_Quantity_Quintals"] < 0).sum())

print("\nNegative quantity flag count:")
print(arrivals["Is_Quantity_Negative_Flag"].sum())

Negative arrival quantities:
0

Negative quantity flag count:
1233

In [33]:
flagged = arrivals[arrivals["Is_Quantity_Negative_Flag"] == 1]

print(flagged[
    [
        "Arrival_ID",
        "Reported_Quantity",
        "Reported_Unit",
        "Arrival_Quantity_Quintals",
        "Arrival_Quantity_Mt",
        "Arrival_Quantity_Kg"
    ]
].head(10))

       Arrival_ID  Reported_Quantity Reported_Unit  Arrival_Quantity_Quintals  \
5      ARR0006341             278.82      Kilogram                     2.7882
10     ARR0024150             205.64      Kilogram                     2.0564
31     ARR0020236             382.93       Quintal                   382.9300
70     ARR0003953             328.28      Kilogram                     3.2828
76   ARR_IMP00420             434.64      Kilogram                     4.3464
90     ARR0008466             494.81      Kilogram                     4.9481
97     ARR0015562              75.94       Quintal                    75.9400
98     ARR0013122              26.99       Quintal                    26.9900
112    ARR0022381             220.44      Kilogram                     2.2044
123    ARR0021309             255.85       Quintal                   255.8500

     Arrival_Quantity_Mt  Arrival_Quantity_Kg
5                 0.2788               278.82
10                0.2056               205.64
31               38.2930             38293.00
70                0.3283               328.28
76                0.4346               434.64
90                0.4948               494.81
97                7.5940              7594.00
98                2.6990              2699.00
112               0.2204               220.44
123              25.5850             25585.00

In [34]:
print("Unique crop names:")
print(sorted(arrivals["Crop_Name"].dropna().unique()))

print("\nNumber of unique crops:")
print(arrivals["Crop_Name"].nunique())

Unique crop names:
['Basmati Rice', 'Cotton', 'Maize', 'Mustard', 'Paddy', 'Rice', 'Sugarcane', 'Wheat']

Number of unique crops:
8

In [35]:
print(arrivals["Crop_Name"].value_counts())

Crop_Name
Wheat           4284
Mustard         4209
Sugarcane       4161
Maize           4155
Cotton          4110
Paddy           1997
Rice            1564
Basmati Rice     520
Name: count, dtype: int64

In [36]:
crop_mapping = {
    "Paddy": "Rice",
    "Basmati Rice": "Rice",
    "Rice": "Rice",
    "Cotton": "Cotton",
    "Maize": "Maize",
    "Mustard": "Mustard",
    "Sugarcane": "Sugarcane",
    "Wheat": "Wheat"
}

arrivals["Crop"] = arrivals["Crop_Name"].map(crop_mapping)

print(arrivals["Crop"].value_counts())

Crop
Wheat        4284
Mustard      4209
Sugarcane    4161
Maize        4155
Cotton       4110
Rice         4081
Name: count, dtype: int64

In [37]:
print(arrivals["Reported_Unit"].value_counts())

Reported_Unit
Quintal         10561
Kilogram         9433
Metric Tonne     5006
Name: count, dtype: int64

In [38]:
print("Checking quantity conversions...")

print(
    "Quintal → KG errors:",
    (
        (arrivals["Arrival_Quantity_Kg"] -
         arrivals["Arrival_Quantity_Quintals"] * 100).abs() > 0.01
    ).sum()
)

print(
    "Quintal → Metric Tonne errors:",
    (
        (arrivals["Arrival_Quantity_Mt"] -
         arrivals["Arrival_Quantity_Quintals"] / 10).abs() > 0.01
    ).sum()
)

Checking quantity conversions...
Quintal → KG errors: 0
Quintal → Metric Tonne errors: 0

In [39]:
total_arrivals = (
    arrivals
    .groupby("Crop")["Arrival_Quantity_Quintals"]
    .sum()
    .sort_values(ascending=False)
)

print("Total arrivals by crop (Quintals):")
print(total_arrivals.round(2))

Total arrivals by crop (Quintals):
Crop
Mustard      1066595.44
Wheat        1060601.59
Sugarcane    1047563.98
Maize        1035612.63
Cotton       1016691.36
Rice         1005242.05
Name: Arrival_Quantity_Quintals, dtype: float64

In [40]:
top_mandis = (
    arrivals
    .groupby("Mandi_ID")["Arrival_Quantity_Quintals"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print("Top 10 mandis by arrival volume:")
print(top_mandis.round(2))

Top 10 mandis by arrival volume:
Mandi_ID
MANDI026    122366.83
MANDI041    121084.19
MANDI002    120648.90
MANDI007    118379.89
MANDI001    117882.38
MANDI048    117052.17
MANDI012    117017.73
MANDI033    116737.79
MANDI039    115113.49
MANDI024    114628.87
Name: Arrival_Quantity_Quintals, dtype: float64

In [41]:
crop_mandi_arrivals = (
    arrivals
    .groupby(["Mandi_ID", "Crop"])["Arrival_Quantity_Quintals"]
    .sum()
    .reset_index()
)

print(crop_mandi_arrivals.head(20))

    Mandi_ID       Crop  Arrival_Quantity_Quintals
0   MANDI001     Cotton                 13786.8400
1   MANDI001      Maize                 20286.5769
2   MANDI001    Mustard                 20963.7039
3   MANDI001       Rice                 20685.0155
4   MANDI001  Sugarcane                 21073.0264
5   MANDI001      Wheat                 21087.2163
6   MANDI002     Cotton                 19229.6300
7   MANDI002      Maize                 14811.2400
8   MANDI002    Mustard                 22069.0422
9   MANDI002       Rice                 18291.8046
10  MANDI002  Sugarcane                 22320.7700
11  MANDI002      Wheat                 23926.4129
12  MANDI003     Cotton                 16470.5014
13  MANDI003      Maize                 17727.6679
14  MANDI003    Mustard                 19069.9962
15  MANDI003       Rice                 16447.2658
16  MANDI003  Sugarcane                 18036.5402
17  MANDI003      Wheat                 14291.0451
18  MANDI004     Cotton                 14436.0306
19  MANDI004      Maize                 16405.5389

In [42]:
mandi_info = mandi[
    ["Mandi_ID", "Mandi_Name", "District", "State"]
].drop_duplicates()

top_mandis_named = (
    top_mandis
    .reset_index()
    .merge(mandi_info, on="Mandi_ID", how="left")
    .rename(columns={
        "Arrival_Quantity_Quintals": "Total_Arrivals_Qtl"
    })
)

print(top_mandis_named)

   Mandi_ID  Total_Arrivals_Qtl                 Mandi_Name       District  \
0  MANDI026         122366.8292            Tadipatri Mandi          Hisar
1  MANDI041         121084.1858       Gurgaon Grain Market      Fatehabad
2  MANDI002         120648.8997              Solapur Mandi       Ludhiana
3  MANDI007         118379.8857               Nashik Mandi       Amritsar
4  MANDI001         117882.3790            Hyderabad Mandi       Ludhiana
5  MANDI048         117052.1657             Chittoor Mandi  Muzaffarnagar
6  MANDI012         117017.7281          Gaya Grain Market        Patiala
7  MANDI033         116737.7926  South Dumdum Grain Market         Ambala
8  MANDI039         115113.4877         Anand Grain Market        Unknown
9  MANDI024         114628.8747               Jaipur Mandi         Karnal

           State
0        Haryana
1        Haryana
2        Unknown
3         Punjab
4         Punjab
5  Uttar Pradesh
6         Punjab
7        Haryana
8        Haryana
9        Haryana

In [44]:
transport = pd.read_csv("cleaned_transport_logistics.csv", sep="\t")

print("Shape:", transport.shape)
print("\nColumns:")
print(transport.columns.tolist())

print("\nMissing values:")
print(transport.isna().sum())

Shape: (10000, 14)

Columns:
['Trip_ID', 'Mandi_ID', 'Destination_Warehouse', 'Departure_Time', 'Arrival_Time', 'Is_Arrival_Time_Imputed', 'Transit_Hours', 'Is_Transit_Hours_Negative_Flag', 'Is_Transit_Hours_Imputed', 'Distance', 'Distance_Unit', 'Vehicle_No', 'Driver_ID', 'Is_Driver_ID_Imputed']

Missing values:
Trip_ID                              0
Mandi_ID                             0
Destination_Warehouse                0
Departure_Time                       0
Arrival_Time                        53
Is_Arrival_Time_Imputed              0
Transit_Hours                      138
Is_Transit_Hours_Negative_Flag       0
Is_Transit_Hours_Imputed             0
Distance                             0
Distance_Unit                      992
Vehicle_No                        1560
Driver_ID                            0
Is_Driver_ID_Imputed                 0
dtype: int64

In [45]:
print("Negative transit-hour records:")
print(
    transport[
        transport["Is_Transit_Hours_Negative_Flag"] == 1
    ][[
        "Trip_ID",
        "Mandi_ID",
        "Departure_Time",
        "Arrival_Time",
        "Transit_Hours",
        "Is_Transit_Hours_Imputed"
    ]].head(10)
)

print("\nTotal negative transit-hour flags:")
print(transport["Is_Transit_Hours_Negative_Flag"].sum())

Negative transit-hour records:
       Trip_ID  Mandi_ID    Departure_Time      Arrival_Time  Transit_Hours  \
18   TRP000019  MANDI046  02-02-2026 16:08  03-02-2026 13:32           21.4
59   TRP000060  MANDI043  02-07-2026 20:51  03-07-2026 16:51           20.0
79   TRP000080  MANDI002  16-04-2026 10:27  16-04-2026 23:33           13.1
83   TRP000084  MANDI023  18-05-2026 18:38  19-05-2026 00:00           22.8
116  TRP000117  MANDI051  02-01-2026 13:16  03-01-2026 12:34           23.3
123  TRP000124  MANDI009  28-04-2026 11:46  29-04-2026 07:34           19.8
151  TRP000152  MANDI022  19-04-2026 20:20  20-04-2026 16:56           20.6
175  TRP000176  MANDI004  08-09-2026 22:29  09-09-2026 12:59           14.5
184  TRP000185  MANDI011  08-01-2026 09:20  09-01-2026 06:32           21.2
187  TRP000188  MANDI035  31-07-2026 00:00  31-07-2026 18:40           18.5

     Is_Transit_Hours_Imputed
18                      False
59                      False
79                      False
83                      False
116                     False
123                     False
151                     False
175                     False
184                     False
187                     False

Total negative transit-hour flags:
539

In [46]:
print("Negative transit hours after cleaning:")
print((transport["Transit_Hours"] < 0).sum())

print("\nMissing transit hours:")
print(transport["Transit_Hours"].isna().sum())

print("\nImputed transit hours:")
print(transport["Is_Transit_Hours_Imputed"].sum())

print("\nTransit hours summary:")
print(transport["Transit_Hours"].describe())

Negative transit hours after cleaning:
0

Missing transit hours:
138

Imputed transit hours:
364

Transit hours summary:
count    9862.000000
mean       12.954045
std         6.310427
min         2.000000
25%         7.600000
50%        13.000000
75%        18.400000
max        24.000000
Name: Transit_Hours, dtype: float64

In [47]:
print("Distance units:")
print(transport["Distance_Unit"].value_counts(dropna=False))

print("\nDistance summary:")
print(transport["Distance"].describe())

Distance units:
Distance_Unit
km       7511
miles    1497
NaN       992
Name: count, dtype: int64

Distance summary:
count     10000
unique     7939
top       523.8
freq          5
Name: Distance, dtype: object

In [48]:
missing_unit = transport[transport["Distance_Unit"].isna()]

print("Records with missing distance unit:")
print(
    missing_unit[
        ["Trip_ID", "Mandi_ID", "Distance", "Distance_Unit"]
    ].head(20)
)

print("\nNumber of missing distance units:")
print(len(missing_unit))

Records with missing distance unit:
       Trip_ID  Mandi_ID   Distance Distance_Unit
3    TRP000004  MANDI038   240.3 KM           NaN
17   TRP000018  MANDI022  1144.2 KM           NaN
18   TRP000019  MANDI046   896.3 KM           NaN
31   TRP000032  MANDI023   632.8 KM           NaN
38   TRP000039  MANDI032   438.6 KM           NaN
54   TRP000055  MANDI024  1078.2 KM           NaN
63   TRP000064  MANDI024   986.5 KM           NaN
64   TRP000065  MANDI057   692.1 KM           NaN
75   TRP000076  MANDI056  1009.3 KM           NaN
79   TRP000080  MANDI002   678.8 KM           NaN
99   TRP000100  MANDI030   566.3 KM           NaN
114  TRP000115  MANDI010   869.2 KM           NaN
128  TRP000129  MANDI025   854.0 KM           NaN
137  TRP000138  MANDI017   131.2 KM           NaN
143  TRP000144  MANDI014   729.8 KM           NaN
155  TRP000156  MANDI033   913.4 KM           NaN
160  TRP000161  MANDI004   524.0 KM           NaN
168  TRP000169  MANDI001   724.9 KM           NaN
169  TRP000170  MANDI029  1024.7 KM           NaN
175  TRP000176  MANDI004   740.0 KM           NaN

Number of missing distance units:
992

In [49]:
# Extract numeric distance from values such as "240.3 KM"
transport["Distance_KM"] = (
    transport["Distance"]
    .astype(str)
    .str.extract(r"([\d.]+)")[0]
    .astype(float)
)

# Convert miles to kilometers
transport.loc[
    transport["Distance_Unit"].str.lower() == "miles",
    "Distance_KM"
] = (
    transport.loc[
        transport["Distance_Unit"].str.lower() == "miles",
        "Distance_KM"
    ] * 1.60934
)

print("Distance_KM summary:")
print(transport["Distance_KM"].describe())

print("\nMissing Distance_KM:")
print(transport["Distance_KM"].isna().sum())

Distance_KM summary:
count    10000.000000
mean       649.587886
std        327.540526
min         81.600000
25%        368.774227
50%        641.000000
75%        906.600000
max       1429.800000
Name: Distance_KM, dtype: float64

Missing Distance_KM:
0

In [50]:
print("Sample vehicle numbers:")
print(transport["Vehicle_No"].dropna().head(20).to_string(index=False))

print("\nUnique vehicle number examples:")
print(transport["Vehicle_No"].dropna().astype(str).unique()[:30])

Sample vehicle numbers:
HR-24-DF-8206
RJ-83-BC-6190
HR-81-DF-8884
PB-12-DF-5486
DL-10-BC-9901
UP-26-CD-2471
RJ-74-CD-5670
HR-98-AB-4542
HR-90-BC-5255
DL-99-DF-7094
PB-72-BC-7175
UP-69-AB-2874
HR-47-CD-6280
RJ-13-BC-6915
HR-76-DF-7435
RJ-54-DF-3193
PB-34-DF-2418
RJ-72-AB-3993
HR-35-AB-5451
DL-86-BC-9195

Unique vehicle number examples:
<StringArray>
['HR-24-DF-8206', 'RJ-83-BC-6190', 'HR-81-DF-8884', 'PB-12-DF-5486',
 'DL-10-BC-9901', 'UP-26-CD-2471', 'RJ-74-CD-5670', 'HR-98-AB-4542',
 'HR-90-BC-5255', 'DL-99-DF-7094', 'PB-72-BC-7175', 'UP-69-AB-2874',
 'HR-47-CD-6280', 'RJ-13-BC-6915', 'HR-76-DF-7435', 'RJ-54-DF-3193',
 'PB-34-DF-2418', 'RJ-72-AB-3993', 'HR-35-AB-5451', 'DL-86-BC-9195',
 'RJ-53-CD-4074', 'UP-30-BC-8937', 'RJ-25-AB-7225', 'HR-88-DF-2151',
 'DL-25-AB-1514', 'RJ-57-CD-7952', 'HR-83-AB-7638', 'PB-19-AB-8250',
 'DL-65-AB-3380', 'HR-55-AB-6191']
Length: 30, dtype: str

In [51]:
transport["Vehicle_No"] = (
    transport["Vehicle_No"]
    .astype("string")
    .str.upper()
    .str.strip()
    .str.replace(r"[\s]+", "-", regex=True)
)

print("Sample standardized vehicle numbers:")
print(transport["Vehicle_No"].dropna().head(20).to_string(index=False))

print("\nMissing vehicle numbers:")
print(transport["Vehicle_No"].isna().sum())

print("\nUnique vehicle numbers:")
print(transport["Vehicle_No"].nunique())

Sample standardized vehicle numbers:
HR-24-DF-8206
RJ-83-BC-6190
HR-81-DF-8884
PB-12-DF-5486
DL-10-BC-9901
UP-26-CD-2471
RJ-74-CD-5670
HR-98-AB-4542
HR-90-BC-5255
DL-99-DF-7094
PB-72-BC-7175
UP-69-AB-2874
HR-47-CD-6280
RJ-13-BC-6915
HR-76-DF-7435
RJ-54-DF-3193
PB-34-DF-2418
RJ-72-AB-3993
HR-35-AB-5451
DL-86-BC-9195

Missing vehicle numbers:
1560

Unique vehicle numbers:
8437

In [52]:
print("Departure time examples:")
print(transport["Departure_Time"].head(10).to_string(index=False))

print("\nArrival time examples:")
print(transport["Arrival_Time"].dropna().head(10).to_string(index=False))

print("\nArrival times imputed:")
print(transport["Is_Arrival_Time_Imputed"].sum())

print("\nMissing arrival times:")
print(transport["Arrival_Time"].isna().sum())

Departure time examples:
25-02-2026 12:53
21-04-2026 22:15
12-08-2026 00:00
28-01-2026 14:28
18-03-2026 21:09
30-04-2026 19:52
13-03-2026 06:40
22-06-2026 04:34
07-08-2026 04:47
02-05-2026 07:23

Arrival time examples:
25-02-2026 17:47
22-04-2026 11:51
12-08-2026 20:30
28-01-2026 18:40
19-03-2026 00:00
30-04-2026 23:28
14-03-2026 01:40
22-06-2026 21:46
08-08-2026 00:53
02-05-2026 15:23

Arrival times imputed:
953

Missing arrival times:
53

In [53]:
missing_arrival = transport[transport["Arrival_Time"].isna()]

print(missing_arrival[[
    "Trip_ID",
    "Mandi_ID",
    "Departure_Time",
    "Arrival_Time",
    "Transit_Hours",
    "Is_Arrival_Time_Imputed",
    "Is_Transit_Hours_Imputed"
]].to_string(index=False))

print("\nNumber of records:", len(missing_arrival))

  Trip_ID Mandi_ID   Departure_Time Arrival_Time  Transit_Hours  Is_Arrival_Time_Imputed  Is_Transit_Hours_Imputed
TRP000037 MANDI040 09-04-2026 16:07          NaN            NaN                    False                     False
TRP000259 MANDI048 24-05-2026 03:42          NaN            NaN                    False                     False
TRP000301 MANDI009 31-03-2026 08:49          NaN            NaN                    False                     False
TRP000712 MANDI037 16-07-2026 15:49          NaN            NaN                    False                     False
TRP000896 MANDI010 10-07-2026 14:13          NaN            NaN                    False                     False
TRP000986 MANDI004 13-06-2026 12:51          NaN            NaN                    False                     False
TRP001104 MANDI032 02-08-2026 00:00          NaN            NaN                    False                     False
TRP001284 MANDI017 27-08-2026 23:18          NaN            NaN                    False                     False
TRP001295 MANDI054 08-05-2026 14:22          NaN            NaN                    False                     False
TRP001335 MANDI015 26-02-2026 08:51          NaN            NaN                    False                     False
TRP001356 MANDI026 22-06-2026 07:38          NaN            NaN                    False                     False
TRP001444 MANDI021 23-06-2026 00:00          NaN            NaN                    False                     False
TRP001709 MANDI017 18-06-2026 16:01          NaN            NaN                    False                     False
TRP002037 MANDI055 27-04-2026 13:32          NaN            NaN                    False                     False
TRP002049 MANDI051 20-01-2026 00:00          NaN            NaN                    False                     False
TRP002139 MANDI013 12-02-2026 06:27          NaN            NaN                    False                     False
TRP002156 MANDI034 15-08-2026 22:06          NaN            NaN                    False                     False
TRP002199 MANDI006 09-08-2026 08:52          NaN            NaN                    False                     False
TRP002309 MANDI018 26-07-2026 06:13          NaN            NaN                    False                     False
TRP002370 MANDI050 19-06-2026 19:00          NaN            NaN                    False                     False
TRP002557 MANDI039 21-01-2026 13:24          NaN            NaN                    False                     False
TRP002749 MANDI046 11-08-2026 22:37          NaN            NaN                    False                     False
TRP003360 MANDI002 31-07-2026 19:04          NaN            NaN                    False                     False
TRP003465 MANDI054 31-07-2026 22:01          NaN            NaN                    False                     False
TRP003480 MANDI017 05-03-2026 21:20          NaN            NaN                    False                     False
TRP003485 MANDI041 04-07-2026 23:38          NaN            NaN                    False                     False
TRP003603 MANDI012 19-04-2026 00:00          NaN            NaN                    False                     False
TRP003843 MANDI017 27-02-2026 03:09          NaN            NaN                    False                     False
TRP003892 MANDI036 11-08-2026 01:29          NaN            NaN                    False                     False
TRP003980 MANDI042 07-04-2026 19:28          NaN            NaN                    False                     False
TRP004605 MANDI047 14-02-2026 12:47          NaN            NaN                    False                     False
TRP005197 MANDI034 02-06-2026 04:20          NaN            NaN                    False                     False
TRP005256 MANDI034 25-04-2026 05:22          NaN            NaN                    False                     False
TRP005746 MANDI044 18-02-2026 19:00          NaN            NaN                    False                     False
TRP005877 MANDI013 04-01-2026 00:00          NaN            NaN                    False                     False
TRP006116 MANDI022 19-04-2026 10:45          NaN            NaN                    False                     False
TRP006139 MANDI020 27-06-2026 03:41          NaN            NaN                    False                     False
TRP006265 MANDI029 01-05-2026 12:23          NaN            NaN                    False                     False
TRP006276 MANDI001 22-01-2026 16:51          NaN            NaN                    False                     False
TRP006559 MANDI051 08-09-2026 22:39          NaN            NaN                    False                     False
TRP006570 MANDI011 19-04-2026 02:35          NaN            NaN                    False                     False
TRP006657 MANDI008 31-08-2026 04:24          NaN            NaN                    False                     False
TRP006881 MANDI029 17-04-2026 19:20          NaN            NaN                    False                     False
TRP006964 MANDI029 05-05-2026 18:33          NaN            NaN                    False                     False
TRP007699 MANDI007 04-05-2026 11:20          NaN            NaN                    False                     False
TRP007793 MANDI037 12-07-2026 22:30          NaN            NaN                    False                     False
TRP008032 MANDI024 14-08-2026 00:00          NaN            NaN                    False                     False
TRP008402 MANDI055 03-04-2026 17:51          NaN            NaN                    False                     False
TRP008948 MANDI006 11-06-2026 04:24          NaN            NaN                    False                     False
TRP009523 MANDI047 09-05-2026 16:48          NaN            NaN                    False                     False
TRP009533 MANDI005 08-05-2026 00:00          NaN            NaN                    False                     False
TRP009602 MANDI024 23-06-2026 00:22          NaN            NaN                    False                     False
TRP009930 MANDI048 09-02-2026 05:25          NaN            NaN                    False                     False

Number of records: 53

In [54]:
transport["Departure_DT"] = pd.to_datetime(
    transport["Departure_Time"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

transport["Arrival_DT"] = pd.to_datetime(
    transport["Arrival_Time"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

calculated_hours = (
    transport["Arrival_DT"] - transport["Departure_DT"]
).dt.total_seconds() / 3600

valid = (
    calculated_hours.notna()
    & transport["Transit_Hours"].notna()
)

difference = (
    calculated_hours[valid] - transport.loc[valid, "Transit_Hours"]
).abs()

print("Records checked:", valid.sum())
print("Maximum difference (hours):", difference.max())
print("Records with difference > 0.2 hours:", (difference > 0.2).sum())

Records checked: 9862
Maximum difference (hours): 23.983333333333334
Records with difference > 0.2 hours: 1538

In [55]:
check = transport.loc[valid, [
    "Trip_ID",
    "Departure_Time",
    "Arrival_Time",
    "Transit_Hours"
]].copy()

check["Calculated_Hours"] = calculated_hours[valid].values
check["Difference"] = (
    check["Calculated_Hours"] - check["Transit_Hours"]
)

print(
    check.reindex(
        check["Difference"].abs().sort_values(ascending=False).index
    ).head(20).to_string(index=False)
)

  Trip_ID   Departure_Time     Arrival_Time  Transit_Hours  Calculated_Hours  Difference
TRP005812 06-04-2026 06:53 06-04-2026 00:00           17.1         -6.883333  -23.983333
TRP001498 14-06-2026 20:41 14-06-2026 00:00            3.3        -20.683333  -23.983333
TRP008979 24-04-2026 00:00 25-04-2026 17:53           17.9         41.883333   23.983333
TRP004651 25-03-2026 00:00 26-03-2026 23:16           23.3         47.266667   23.966667
TRP004068 15-01-2026 10:56 15-01-2026 00:00           13.0        -10.933333  -23.933333
TRP002916 24-02-2026 00:00 25-02-2026 16:48           16.9         40.800000   23.900000
TRP005311 21-05-2026 00:00 22-05-2026 04:30            4.6         28.500000   23.900000
TRP009738 03-06-2026 07:54 03-06-2026 00:00           16.0         -7.900000  -23.900000
TRP005766 24-08-2026 10:52 24-08-2026 00:00           13.0        -10.866667  -23.866667
TRP005525 04-06-2026 00:00 05-06-2026 12:50           13.0         36.833333   23.833333
TRP000229 24-01-2026 19:14 24-01-2026 00:00            4.6        -19.233333  -23.833333
TRP003765 23-03-2026 21:29 23-03-2026 00:00            2.3        -21.483333  -23.783333
TRP009895 26-02-2026 11:59 26-02-2026 00:00           11.8        -11.983333  -23.783333
TRP002845 24-06-2026 11:34 24-06-2026 00:00           12.2        -11.566667  -23.766667
TRP002936 03-09-2026 00:00 04-09-2026 03:51            4.1         27.850000   23.750000
TRP003345 28-01-2026 00:00 29-01-2026 12:39           12.9         36.650000   23.750000
TRP005284 25-03-2026 00:00 26-03-2026 03:09            3.4         27.150000   23.750000
TRP005809 08-05-2026 11:26 08-05-2026 00:00           12.3        -11.433333  -23.733333
TRP005394 10-06-2026 00:08 10-06-2026 00:00           23.6         -0.133333  -23.733333
TRP008436 10-08-2026 00:00 11-08-2026 23:37           23.9         47.616667   23.716667

In [56]:
print("Negative Transit_Hours:", (transport["Transit_Hours"] < 0).sum())
print("Transit_Hours below 2:", (transport["Transit_Hours"] < 2).sum())
print("Transit_Hours above 24:", (transport["Transit_Hours"] > 24).sum())
print("Missing Transit_Hours:", transport["Transit_Hours"].isna().sum())

print("\nTransit Hours Summary:")
print(transport["Transit_Hours"].describe())

Negative Transit_Hours: 0
Transit_Hours below 2: 0
Transit_Hours above 24: 0
Missing Transit_Hours: 138

Transit Hours Summary:
count    9862.000000
mean       12.954045
std         6.310427
min         2.000000
25%         7.600000
50%        13.000000
75%        18.400000
max        24.000000
Name: Transit_Hours, dtype: float64

In [57]:
transit_by_warehouse = (
    transport
    .dropna(subset=["Transit_Hours"])
    .groupby("Destination_Warehouse")
    .agg(
        Avg_Transit_Hours=("Transit_Hours", "mean"),
        Trips=("Trip_ID", "count")
    )
    .sort_values("Avg_Transit_Hours", ascending=False)
)

print(transit_by_warehouse.round(2))

                       Avg_Transit_Hours  Trips
Destination_Warehouse
WH-East                            13.05   1587
WH-West                            13.04   1655
WH-Central                         13.01   1640
WH-North                           12.97   1690
Export-Terminal                    12.87   1620
WH-South                           12.80   1670

In [58]:
delay_threshold = 18

transport["Transit_Delayed"] = (
    transport["Transit_Hours"] > delay_threshold
)

valid_transit = transport["Transit_Hours"].notna()

delay_count = transport.loc[
    valid_transit, "Transit_Delayed"
].sum()

delay_rate = (
    delay_count / valid_transit.sum()
) * 100

print("Delay threshold:", delay_threshold, "hours")
print("Delayed trips:", delay_count)
print("Valid transit records:", valid_transit.sum())
print("Transit delay rate:", round(delay_rate, 2), "%")

Delay threshold: 18 hours
Delayed trips: 2620
Valid transit records: 9862
Transit delay rate: 26.57 %

In [59]:
print("Arrival date range:")
print("Start:", arrivals["Date"].min())
print("End:", arrivals["Date"].max())

print("\nUnique arrival dates:")
print(arrivals["Date"].nunique())

Arrival date range:
Start: 01-01-2026
End: 31-08-2026

Unique arrival dates:
276

In [60]:
print(arrivals["Date"].dtype)
print(arrivals["Date"].head())

str
0    23-06-2026
1    26-04-2026
2    31-05-2026
3    07-09-2026
4    14-04-2026
Name: Date, dtype: str

In [62]:
arrivals["Date"] = pd.to_datetime(
    arrivals["Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

print("Arrival date range:")
print("Start:", arrivals["Date"].min())
print("End:", arrivals["Date"].max())

print("\nMissing arrival dates:")
print(arrivals["Date"].isna().sum())

Arrival date range:
Start: NaT
End: NaT

Missing arrival dates:
25000

In [63]:
arrivals = pd.read_csv(
    "cleaned_mandi_arrivals.csv",
    sep="\t"
)

print(arrivals["Date"].head())
print(arrivals["Date"].dtype)

0    23-06-2026
1    26-04-2026
2    31-05-2026
3    07-09-2026
4    14-04-2026
Name: Date, dtype: str
str

In [64]:
arrivals["Date"] = pd.to_datetime(
    arrivals["Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

print("Arrival date range:")
print("Start:", arrivals["Date"].min())
print("End:", arrivals["Date"].max())

print("\nMissing arrival dates:")
print(arrivals["Date"].isna().sum())

Arrival date range:
Start: 2026-01-01 00:00:00
End: 2026-12-08 00:00:00

Missing arrival dates:
0

In [66]:
crop_mapping = {
    "Paddy": "Rice",
    "Basmati Rice": "Rice",
    "Rice": "Rice",
    "Cotton": "Cotton",
    "Maize": "Maize",
    "Mustard": "Mustard",
    "Sugarcane": "Sugarcane",
    "Wheat": "Wheat"
}

arrivals["Crop"] = arrivals["Crop_Name"].map(crop_mapping)

print("Crop values:")
print(arrivals["Crop"].value_counts())

print("\nMissing standardized crops:")
print(arrivals["Crop"].isna().sum())

Crop values:
Crop
Wheat        4284
Mustard      4209
Sugarcane    4161
Maize        4155
Cotton       4110
Rice         4081
Name: count, dtype: int64

Missing standardized crops:
0

In [67]:
arrival_daily = (
    arrivals
    .groupby(
        ["Date", "Mandi_ID", "Crop"],
        as_index=False
    )
    .agg(
        Total_Arrivals_Qtl=("Arrival_Quantity_Quintals", "sum"),
        Farmer_Count=("Farmer_Count", "sum"),
        Arrival_Records=("Arrival_ID", "count")
    )
)

print("Arrival daily shape:")
print(arrival_daily.shape)

print("\nColumns:")
print(arrival_daily.columns.tolist())

print("\nSample:")
print(arrival_daily.head())

Arrival daily shape:
(21750, 6)

Columns:
['Date', 'Mandi_ID', 'Crop', 'Total_Arrivals_Qtl', 'Farmer_Count', 'Arrival_Records']

Sample:
        Date  Mandi_ID       Crop  Total_Arrivals_Qtl  Farmer_Count  \
0 2026-01-01  MANDI001      Maize              232.56          62.0
1 2026-01-01  MANDI001  Sugarcane              499.91          83.0
2 2026-01-01  MANDI003    Mustard               46.01          62.0
3 2026-01-01  MANDI004  Sugarcane              428.33         145.0
4 2026-01-01  MANDI005       Rice              112.64           0.0

   Arrival_Records
0                2
1                1
2                1
3                1
4                1

In [68]:
# Make sure both datasets use the same date format
arrival_daily["Date"] = pd.to_datetime(arrival_daily["Date"]).dt.normalize()
final_data["date"] = pd.to_datetime(final_data["date"]).dt.normalize()

# Merge arrival information into our existing master dataset
master_data = final_data.merge(
    arrival_daily,
    left_on=["date", "Mandi_ID", "Crop"],
    right_on=["Date", "Mandi_ID", "Crop"],
    how="left"
)

# Remove duplicate date column
master_data = master_data.drop(columns=["Date"])

print("Master dataset shape:")
print(master_data.shape)

print("\nColumns:")
print(master_data.columns.tolist())

print("\nSample:")
print(master_data.head())

Master dataset shape:
(10164, 20)

Columns:
['date', 'Mandi_ID', 'Crop', 'Min_Price', 'Max_Price', 'Modal_Price', 'MSP', 'Mandi_Name', 'District', 'State', 'Mandi_Type', 'Total_Area_Acres', 'Avg_Temperature_C', 'Total_Rainfall_mm', 'Avg_Humidity', 'Sensor_Count', 'Price_Crash', 'Total_Arrivals_Qtl', 'Farmer_Count', 'Arrival_Records']

Sample:
        date  Mandi_ID    Crop  Min_Price  Max_Price  Modal_Price     MSP  \
0 2026-01-01  MANDI001  Cotton    6314.00    7889.00          NaN  6620.0
1 2026-01-01  MANDI003    Rice        NaN    2495.95      2248.00     NaN
2 2026-01-01  MANDI004  Cotton    6673.83    7825.48      7249.66  6620.0
3 2026-01-01  MANDI004   Wheat    1997.69        NaN      2063.64  2275.0
4 2026-01-01  MANDI005  Cotton    6102.20    6418.63          NaN  6620.0

              Mandi_Name  District   State Mandi_Type  Total_Area_Acres  \
0        Hyderabad Mandi  Ludhiana  Punjab    PRIVATE              11.0
1       Vijayawada Mandi  Ludhiana  Punjab       APMC              19.0
2   Khandwa Grain Market  Ludhiana  Punjab       APMC              15.0
3   Khandwa Grain Market  Ludhiana  Punjab       APMC              15.0
4  Bhilwara Grain Market  Amritsar  Punjab     DIRECT              29.0

   Avg_Temperature_C  Total_Rainfall_mm  Avg_Humidity  Sensor_Count  \
0          28.445849             1166.7      62.97561          36.0
1          28.445849             1166.7      62.97561          36.0
2          28.445849             1166.7      62.97561          36.0
3          28.445849             1166.7      62.97561          36.0
4          28.445849             1166.7      62.97561          36.0

   Price_Crash  Total_Arrivals_Qtl  Farmer_Count  Arrival_Records
0        False                 NaN           NaN              NaN
1        False                 NaN           NaN              NaN
2        False                 NaN           NaN              NaN
3         True                 NaN           NaN              NaN
4        False                 NaN           NaN              NaN

In [69]:
print("Total master records:", len(master_data))

print(
    "Records with arrival data:",
    master_data["Total_Arrivals_Qtl"].notna().sum()
)

print(
    "Records without arrival data:",
    master_data["Total_Arrivals_Qtl"].isna().sum()
)

print(
    "Arrival data coverage:",
    round(
        master_data["Total_Arrivals_Qtl"].notna().mean() * 100,
        2
    ),
    "%"
)

Total master records: 10164
Records with arrival data: 2444
Records without arrival data: 7720
Arrival data coverage: 24.05 %

In [70]:
print("Price/Weather master date range:")
print("Start:", final_data["date"].min())
print("End:", final_data["date"].max())

print("\nArrival date range:")
print("Start:", arrival_daily["Date"].min())
print("End:", arrival_daily["Date"].max())

print("\nUnique dates:")
print("Master:", final_data["date"].nunique())
print("Arrivals:", arrival_daily["Date"].nunique())

print("\nUnique mandis:")
print("Master:", final_data["Mandi_ID"].nunique())
print("Arrivals:", arrival_daily["Mandi_ID"].nunique())

print("\nUnique crops:")
print("Master:", final_data["Crop"].nunique())
print("Arrivals:", arrival_daily["Crop"].nunique())

Price/Weather master date range:
Start: 2026-01-01 00:00:00
End: 2026-12-08 00:00:00

Arrival date range:
Start: 2026-01-01 00:00:00
End: 2026-12-08 00:00:00

Unique dates:
Master: 276
Arrivals: 276

Unique mandis:
Master: 57
Arrivals: 57

Unique crops:
Master: 6
Arrivals: 6

In [71]:
# Create the unique combinations in each dataset
master_keys = final_data[
    ["date", "Mandi_ID", "Crop"]
].drop_duplicates()

arrival_keys = arrival_daily[
    ["Date", "Mandi_ID", "Crop"]
].drop_duplicates()

# Rename Date so both key sets match
arrival_keys = arrival_keys.rename(columns={"Date": "date"})

# Find combinations that exist in both datasets
matched_keys = master_keys.merge(
    arrival_keys,
    on=["date", "Mandi_ID", "Crop"],
    how="inner"
)

print("Unique master combinations:", len(master_keys))
print("Unique arrival combinations:", len(arrival_keys))
print("Matching combinations:", len(matched_keys))

print(
    "Combination match rate:",
    round(len(matched_keys) / len(master_keys) * 100, 2),
    "%"
)

Unique master combinations: 10164
Unique arrival combinations: 21750
Matching combinations: 2444
Combination match rate: 24.05 %

In [72]:
print("Arrival quantity missing:")
print(master_data["Total_Arrivals_Qtl"].isna().sum())

print("\nArrival quantity statistics:")
print(master_data["Total_Arrivals_Qtl"].describe())

print("\nNegative arrival quantities:")
print(
    (master_data["Total_Arrivals_Qtl"] < 0).sum()
)

print("\nArrival records missing:")
print(master_data["Arrival_Records"].isna().sum())

Arrival quantity missing:
7720

Arrival quantity statistics:
count    2444.000000
mean      284.921070
std       182.444321
min         0.199600
25%       136.735000
50%       269.505000
75%       413.417500
max      1241.280000
Name: Total_Arrivals_Qtl, dtype: float64

Negative arrival quantities:
0

Arrival records missing:
7720

In [73]:
supply_price = master_data[
    master_data["Total_Arrivals_Qtl"].notna() &
    master_data["Modal_Price"].notna()
].copy()

crop_supply_price = (
    supply_price
    .groupby("Crop")
    .agg(
        Total_Arrivals_Qtl=("Total_Arrivals_Qtl", "sum"),
        Avg_Modal_Price=("Modal_Price", "mean"),
        Records=("Crop", "count")
    )
    .sort_values("Total_Arrivals_Qtl", ascending=False)
)

print(crop_supply_price.round(2))

           Total_Arrivals_Qtl  Avg_Modal_Price  Records
Crop
Wheat               122685.26          2325.94      424
Mustard             122635.36          5793.96      407
Sugarcane           107933.00          3588.02      377
Maize               104659.76          2126.92      377
Rice                102812.62          2232.92      372
Cotton              100588.04          6732.35      367

In [74]:
supply_price["Price_Gap"] = (
    supply_price["Modal_Price"] - supply_price["MSP"]
)

supply_price["Price_Gap_%"] = (
    supply_price["Price_Gap"]
    / supply_price["MSP"]
    * 100
)

crop_supply_msp = (
    supply_price
    .groupby("Crop")
    .agg(
        Total_Arrivals_Qtl=("Total_Arrivals_Qtl", "sum"),
        Avg_Modal_Price=("Modal_Price", "mean"),
        Avg_MSP=("MSP", "mean"),
        Avg_Price_Gap=("Price_Gap", "mean"),
        Avg_Price_Gap_Percent=("Price_Gap_%", "mean")
    )
    .sort_values("Avg_Price_Gap_Percent")
)

print(crop_supply_msp.round(2))

           Total_Arrivals_Qtl  Avg_Modal_Price  Avg_MSP  Avg_Price_Gap  \
Crop
Cotton              100588.04          6732.35   6620.0         112.89
Maize               104659.76          2126.92   2090.0          36.08
Wheat               122685.26          2325.94   2275.0          48.06
Rice                102812.62          2232.92   2183.0          47.82
Sugarcane           107933.00          3588.02   3500.0          84.26
Mustard             122635.36          5793.96   5650.0         153.11

           Avg_Price_Gap_Percent
Crop
Cotton                      1.71
Maize                       1.73
Wheat                       2.11
Rice                        2.19
Sugarcane                   2.41
Mustard                     2.71

In [75]:
valid_price = master_data[
    master_data["Modal_Price"].notna() &
    master_data["MSP"].notna()
].copy()

crash_by_crop = (
    valid_price
    .groupby("Crop")
    .agg(
        Price_Crash_Instances=("Price_Crash", "sum"),
        Valid_Price_Records=("Price_Crash", "count")
    )
)

crash_by_crop["Crash_Rate_%"] = (
    crash_by_crop["Price_Crash_Instances"]
    / crash_by_crop["Valid_Price_Records"]
    * 100
)

crash_by_crop = crash_by_crop.sort_values(
    "Crash_Rate_%",
    ascending=False
)

print(crash_by_crop.round(2))

           Price_Crash_Instances  Valid_Price_Records  Crash_Rate_%
Crop
Wheat                        542                 1289         42.05
Maize                        539                 1340         40.22
Rice                         508                 1290         39.38
Cotton                       508                 1299         39.11
Mustard                      501                 1315         38.10
Sugarcane                    481                 1285         37.43

In [76]:
mandi_crop_risk = (
    valid_price
    .groupby(["Mandi_ID", "Crop"])
    .agg(
        Crash_Instances=("Price_Crash", "sum"),
        Valid_Records=("Price_Crash", "count"),
        Avg_Modal_Price=("Modal_Price", "mean"),
        Avg_MSP=("MSP", "mean")
    )
    .reset_index()
)

mandi_crop_risk["Crash_Rate_%"] = (
    mandi_crop_risk["Crash_Instances"]
    / mandi_crop_risk["Valid_Records"]
    * 100
)

mandi_crop_risk = mandi_crop_risk[
    mandi_crop_risk["Valid_Records"] >= 10
].sort_values(
    "Crash_Rate_%",
    ascending=False
)

print(mandi_crop_risk.head(15).round(2))

     Mandi_ID       Crop  Crash_Instances  Valid_Records  Avg_Modal_Price  \
39   MANDI007       Rice               15             22          2146.48
22   MANDI004  Sugarcane               14             21          3465.61
83   MANDI014      Wheat               10             16          2246.69
249  MANDI042       Rice               13             21          2220.34
119  MANDI020      Wheat               14             23          2271.11
109  MANDI019      Maize               17             28          2089.50
274  MANDI046  Sugarcane               12             20          3476.36
330  MANDI056     Cotton               15             25          6674.29
91   MANDI016      Maize               13             22          2090.94
252  MANDI043     Cotton               10             17          6619.24
244  MANDI041  Sugarcane               17             29          3512.90
199  MANDI034      Maize               11             19          2078.73
23   MANDI004      Wheat               11             19          2304.40
31   MANDI006      Maize               15             26          2113.46
306  MANDI052     Cotton               13             23          6501.41

     Avg_MSP  Crash_Rate_%
39    2183.0         68.18
22    3500.0         66.67
83    2275.0         62.50
249   2183.0         61.90
119   2275.0         60.87
109   2090.0         60.71
274   3500.0         60.00
330   6620.0         60.00
91    2090.0         59.09
252   6620.0         58.82
244   3500.0         58.62
199   2090.0         57.89
23    2275.0         57.89
31    2090.0         57.69
306   6620.0         56.52

In [77]:
supply_crash_analysis = (
    valid_price[
        valid_price["Total_Arrivals_Qtl"].notna()
    ]
    .groupby(["Crop", "Price_Crash"])
    .agg(
        Avg_Arrivals_Qtl=("Total_Arrivals_Qtl", "mean"),
        Records=("Price_Crash", "count")
    )
    .reset_index()
)

print(supply_crash_analysis.round(2))

         Crop  Price_Crash  Avg_Arrivals_Qtl  Records
0      Cotton        False            277.45      173
1      Cotton         True            279.32      122
2       Maize        False            289.78      180
3       Maize         True            275.96      116
4     Mustard        False            300.22      205
5     Mustard         True            296.40      118
6        Rice        False            283.14      186
7        Rice         True            264.12      115
8   Sugarcane        False            284.88      183
9   Sugarcane         True            276.61      116
10      Wheat        False            294.26      202
11      Wheat         True            267.14      130

In [78]:
weather_arrivals = (
    master_data[
        master_data["Total_Arrivals_Qtl"].notna() &
        master_data["Total_Rainfall_mm"].notna()
    ]
    .groupby("date")
    .agg(
        Total_Arrivals_Qtl=("Total_Arrivals_Qtl", "sum"),
        Rainfall_mm=("Total_Rainfall_mm", "first")
    )
    .reset_index()
)

correlation = weather_arrivals[
    ["Total_Arrivals_Qtl", "Rainfall_mm"]
].corr().iloc[0, 1]

print("Rainfall–Arrival Correlation:", round(correlation, 3))
print("\nDaily weather-arrival data:")
print(weather_arrivals.head())

Rainfall–Arrival Correlation: 0.022

Daily weather-arrival data:
        date  Total_Arrivals_Qtl  Rainfall_mm
0 2026-01-01           1856.7700      1166.70
1 2026-01-02           2941.4714      1342.26
2 2026-01-03           4060.9500      1480.12
3 2026-01-04           1307.8732      1376.79
4 2026-01-05           2088.5300      1351.94

In [79]:
transport_mandi = transport.merge(
    mandi[["Mandi_ID", "Mandi_Name", "District", "State"]],
    on="Mandi_ID",
    how="left"
)

transport_mandi_summary = (
    transport_mandi
    .dropna(subset=["Transit_Hours"])
    .groupby(["Mandi_ID", "Mandi_Name"])
    .agg(
        Avg_Transit_Hours=("Transit_Hours", "mean"),
        Avg_Distance_KM=("Distance_KM", "mean"),
        Trips=("Trip_ID", "count")
    )
    .sort_values("Avg_Transit_Hours", ascending=False)
)

print(transport_mandi_summary.head(15).round(2))

                                    Avg_Transit_Hours  Avg_Distance_KM  Trips
Mandi_ID Mandi_Name
MANDI047 Orai Market                            14.07           698.10    157
MANDI029 Asansol Grain Market                   13.98           685.17    172
MANDI002 Solapur Mandi                          13.95           694.03    171
MANDI033 South Dumdum Grain Market              13.90           708.99    160
MANDI007 Nashik Mandi                           13.63           679.58    175
MANDI006 Kochi Mandi                            13.55           685.59    170
MANDI051 Gulbarga Market                        13.47           680.22    162
MANDI023 Panihati APMC                          13.47           665.36    175
MANDI041 Gurgaon Grain Market                   13.46           674.58    182
MANDI011 Arrah Mandi                            13.44           667.41    213
MANDI037 Jorhat Grain Market                    13.44           677.83    192
MANDI014 Bathinda Grain Market                  13.37           663.31    164
MANDI055 Chandigarh APMC                        13.36           666.48    172
MANDI017 Parbhani Market                        13.27           659.27    183
MANDI013 Aurangabad Market                      13.26           671.35    153

In [80]:
warehouse_delay = (
    transport
    .dropna(subset=["Transit_Hours"])
    .assign(
        Delayed=lambda x: x["Transit_Hours"] > 18
    )
    .groupby("Destination_Warehouse")
    .agg(
        Total_Trips=("Trip_ID", "count"),
        Delayed_Trips=("Delayed", "sum"),
        Avg_Transit_Hours=("Transit_Hours", "mean")
    )
    .reset_index()
)

warehouse_delay["Delay_Rate_%"] = (
    warehouse_delay["Delayed_Trips"]
    / warehouse_delay["Total_Trips"]
    * 100
)

warehouse_delay = warehouse_delay.sort_values(
    "Delay_Rate_%",
    ascending=False
)

print(warehouse_delay.round(2))

  Destination_Warehouse  Total_Trips  Delayed_Trips  Avg_Transit_Hours  \
5               WH-West         1655            454              13.04
3              WH-North         1690            461              12.97
1            WH-Central         1640            438              13.01
2               WH-East         1587            420              13.05
0       Export-Terminal         1620            428              12.87
4              WH-South         1670            419              12.80

   Delay_Rate_%
5         27.43
3         27.28
1         26.71
2         26.47
0         26.42
4         25.09

In [81]:
mandi_risk = (
    master_data[
        master_data["Modal_Price"].notna() &
        master_data["MSP"].notna()
    ]
    .groupby(["Mandi_ID", "Mandi_Name"])
    .agg(
        Price_Crash_Rate=("Price_Crash", "mean"),
        Avg_Arrivals_Qtl=("Total_Arrivals_Qtl", "mean"),
        Records=("Price_Crash", "count")
    )
    .reset_index()
)

mandi_risk["Price_Crash_Rate_%"] = (
    mandi_risk["Price_Crash_Rate"] * 100
)

mandi_risk = mandi_risk[
    mandi_risk["Records"] >= 10
].sort_values(
    "Price_Crash_Rate_%",
    ascending=False
)

print(
    mandi_risk[
        [
            "Mandi_ID",
            "Mandi_Name",
            "Price_Crash_Rate_%",
            "Avg_Arrivals_Qtl",
            "Records"
        ]
    ].head(15).round(2)
)

    Mandi_ID                 Mandi_Name  Price_Crash_Rate_%  Avg_Arrivals_Qtl  \
45  MANDI046           Baranagar Market               47.79            255.67
3   MANDI004       Khandwa Grain Market               46.88            290.72
13  MANDI014      Bathinda Grain Market               45.77            255.67
18  MANDI019    Karimnagar Grain Market               45.69            257.63
43  MANDI044                Dehri Mandi               45.67            335.93
26  MANDI027                 Kochi APMC               45.07            298.05
27  MANDI028         Machilipatnam APMC               43.28            270.41
54  MANDI055            Chandigarh APMC               43.28            257.25
37  MANDI038            Jalandhar Mandi               43.28            302.18
40  MANDI041       Gurgaon Grain Market               42.68            324.67
17  MANDI018              Jaunpur Mandi               42.42            294.79
2   MANDI003           Vijayawada Mandi               42.40            282.78
32  MANDI033  South Dumdum Grain Market               42.18            303.20
46  MANDI047                Orai Market               42.06            329.65
34  MANDI035             Guntakal Mandi               42.03            329.42

    Records
45      136
3       128
13      142
18      116
43      127
26      142
27      134
54      134
37      134
40      157
17      132
2       125
32      147
46      126
34      138

In [82]:
# Create a simple 0–100 risk score for each mandi

mandi_risk["Price_Risk_Score"] = (
    mandi_risk["Price_Crash_Rate_%"]
    / mandi_risk["Price_Crash_Rate_%"].max()
    * 100
)

mandi_risk["Supply_Score"] = (
    mandi_risk["Avg_Arrivals_Qtl"]
    / mandi_risk["Avg_Arrivals_Qtl"].max()
    * 100
)

# Higher supply + higher price risk = greater intervention priority
mandi_risk["Priority_Score"] = (
    0.6 * mandi_risk["Price_Risk_Score"] +
    0.4 * mandi_risk["Supply_Score"]
)

mandi_risk = mandi_risk.sort_values(
    "Priority_Score",
    ascending=False
)

print(
    mandi_risk[
        [
            "Mandi_ID",
            "Mandi_Name",
            "Price_Crash_Rate_%",
            "Avg_Arrivals_Qtl",
            "Priority_Score"
        ]
    ].head(15).round(2)
)

    Mandi_ID                 Mandi_Name  Price_Crash_Rate_%  Avg_Arrivals_Qtl  \
43  MANDI044                Dehri Mandi               45.67            335.93
3   MANDI004       Khandwa Grain Market               46.88            290.72
26  MANDI027                 Kochi APMC               45.07            298.05
40  MANDI041       Gurgaon Grain Market               42.68            324.67
46  MANDI047                Orai Market               42.06            329.65
34  MANDI035             Guntakal Mandi               42.03            329.42
45  MANDI046           Baranagar Market               47.79            255.67
49  MANDI050                Durg Market               40.16            339.12
37  MANDI038            Jalandhar Mandi               43.28            302.18
10  MANDI011                Arrah Mandi               37.31            368.43
32  MANDI033  South Dumdum Grain Market               42.18            303.20
55  MANDI056             Bilaspur Mandi               40.27            324.00
18  MANDI019    Karimnagar Grain Market               45.69            257.63
17  MANDI018              Jaunpur Mandi               42.42            294.79
13  MANDI014      Bathinda Grain Market               45.77            255.67

    Priority_Score
43           93.80
3            90.41
26           88.94
40           88.82
46           88.60
34           88.53
45           87.76
49           87.24
37           87.14
10           86.84
32           85.87
55           85.73
18           85.33
17           85.26
13           85.22

In [83]:
# Calculate average transit time for each mandi
transport_mandi_risk = (
    transport
    .dropna(subset=["Transit_Hours"])
    .groupby("Mandi_ID")
    .agg(
        Avg_Transit_Hours=("Transit_Hours", "mean"),
        Total_Trips=("Trip_ID", "count"),
        Delayed_Trips=("Transit_Hours", lambda x: (x > 18).sum())
    )
    .reset_index()
)

transport_mandi_risk["Delay_Rate_%"] = (
    transport_mandi_risk["Delayed_Trips"]
    / transport_mandi_risk["Total_Trips"]
    * 100
)

# Add transport information to our mandi risk table
mandi_risk_final = mandi_risk.merge(
    transport_mandi_risk,
    on="Mandi_ID",
    how="left"
)

print(
    mandi_risk_final[
        [
            "Mandi_ID",
            "Mandi_Name",
            "Price_Crash_Rate_%",
            "Avg_Arrivals_Qtl",
            "Avg_Transit_Hours",
            "Delay_Rate_%"
        ]
    ].sort_values(
        "Delay_Rate_%",
        ascending=False
    ).head(15).round(2)
)

    Mandi_ID                 Mandi_Name  Price_Crash_Rate_%  Avg_Arrivals_Qtl  \
41  MANDI051            Gulbarga Market               38.35            264.87
4   MANDI047                Orai Market               42.06            329.65
51  MANDI037        Jorhat Grain Market               35.48            259.18
15  MANDI025              Dindigul APMC               39.74            319.41
9   MANDI011                Arrah Mandi               37.31            368.43
16  MANDI022                 Eluru APMC               40.15            312.72
47  MANDI012          Gaya Grain Market               37.10            268.80
49  MANDI029       Asansol Grain Market               40.00            230.74
10  MANDI033  South Dumdum Grain Market               42.18            303.20
7   MANDI050                Durg Market               40.16            339.12
54  MANDI023              Panihati APMC               29.63            282.18
42  MANDI054   Nangloi Jat Grain Market               36.43            286.10
28  MANDI002              Solapur Mandi               38.96            283.68
5   MANDI035             Guntakal Mandi               42.03            329.42
3   MANDI041       Gurgaon Grain Market               42.68            324.67

    Avg_Transit_Hours  Delay_Rate_%
41              13.47         34.57
4               14.07         33.76
51              13.44         32.29
15              13.15         32.12
9               13.44         31.92
16              13.08         31.55
47              12.84         30.81
49              13.98         30.23
10              13.90         30.00
7               13.21         29.83
54              13.47         29.71
42              13.07         29.63
28              13.95         29.24
5               13.17         29.14
3               13.46         29.12

In [84]:
# Normalize the three risk factors to 0–100

mandi_risk_final["Price_Risk_Score"] = (
    mandi_risk_final["Price_Crash_Rate_%"]
    / mandi_risk_final["Price_Crash_Rate_%"].max()
    * 100
)

mandi_risk_final["Supply_Pressure_Score"] = (
    mandi_risk_final["Avg_Arrivals_Qtl"]
    / mandi_risk_final["Avg_Arrivals_Qtl"].max()
    * 100
)

mandi_risk_final["Transport_Risk_Score"] = (
    mandi_risk_final["Delay_Rate_%"]
    / mandi_risk_final["Delay_Rate_%"].max()
    * 100
)

# Final optimizer priority score
mandi_risk_final["Priority_Score"] = (
    0.50 * mandi_risk_final["Price_Risk_Score"] +
    0.30 * mandi_risk_final["Supply_Pressure_Score"] +
    0.20 * mandi_risk_final["Transport_Risk_Score"]
)

final_priority = (
    mandi_risk_final
    .sort_values("Priority_Score", ascending=False)
)

print(
    final_priority[
        [
            "Mandi_ID",
            "Mandi_Name",
            "Price_Crash_Rate_%",
            "Avg_Arrivals_Qtl",
            "Delay_Rate_%",
            "Priority_Score"
        ]
    ].head(15).round(2)
)

    Mandi_ID                 Mandi_Name  Price_Crash_Rate_%  Avg_Arrivals_Qtl  \
4   MANDI047                Orai Market               42.06            329.65
1   MANDI004       Khandwa Grain Market               46.88            290.72
0   MANDI044                Dehri Mandi               45.67            335.93
3   MANDI041       Gurgaon Grain Market               42.68            324.67
5   MANDI035             Guntakal Mandi               42.03            329.42
9   MANDI011                Arrah Mandi               37.31            368.43
2   MANDI027                 Kochi APMC               45.07            298.05
7   MANDI050                Durg Market               40.16            339.12
10  MANDI033  South Dumdum Grain Market               42.18            303.20
15  MANDI025              Dindigul APMC               39.74            319.41
16  MANDI022                 Eluru APMC               40.15            312.72
6   MANDI046           Baranagar Market               47.79            255.67
14  MANDI014      Bathinda Grain Market               45.77            255.67
8   MANDI038            Jalandhar Mandi               43.28            302.18
11  MANDI056             Bilaspur Mandi               40.27            324.00

    Delay_Rate_%  Priority_Score
4          33.76           90.38
1          28.31           89.09
0          23.98           89.00
3          29.12           87.93
5          29.14           87.65
9          31.92           87.51
2          27.47           87.31
7          29.83           86.89
10         30.00           86.17
15         32.12           86.16
16         31.55           85.72
6          25.53           85.59
14         28.05           84.93
8          22.58           82.95
11         24.87           82.90

In [85]:
# Select the final optimizer scores
optimizer_scores = mandi_risk_final[
    [
        "Mandi_ID",
        "Price_Risk_Score",
        "Supply_Pressure_Score",
        "Transport_Risk_Score",
        "Priority_Score"
    ]
].drop_duplicates("Mandi_ID")

# Add optimizer scores to the integrated dataset
powerbi_data = master_data.merge(
    optimizer_scores,
    on="Mandi_ID",
    how="left"
)

print("Power BI dataset shape:", powerbi_data.shape)
print("\nColumns:")
print(powerbi_data.columns.tolist())

print("\nPreview:")
print(powerbi_data.head())

Power BI dataset shape: (10164, 24)

Columns:
['date', 'Mandi_ID', 'Crop', 'Min_Price', 'Max_Price', 'Modal_Price', 'MSP', 'Mandi_Name', 'District', 'State', 'Mandi_Type', 'Total_Area_Acres', 'Avg_Temperature_C', 'Total_Rainfall_mm', 'Avg_Humidity', 'Sensor_Count', 'Price_Crash', 'Total_Arrivals_Qtl', 'Farmer_Count', 'Arrival_Records', 'Price_Risk_Score', 'Supply_Pressure_Score', 'Transport_Risk_Score', 'Priority_Score']

Preview:
        date  Mandi_ID    Crop  Min_Price  Max_Price  Modal_Price     MSP  \
0 2026-01-01  MANDI001  Cotton    6314.00    7889.00          NaN  6620.0
1 2026-01-01  MANDI003    Rice        NaN    2495.95      2248.00     NaN
2 2026-01-01  MANDI004  Cotton    6673.83    7825.48      7249.66  6620.0
3 2026-01-01  MANDI004   Wheat    1997.69        NaN      2063.64  2275.0
4 2026-01-01  MANDI005  Cotton    6102.20    6418.63          NaN  6620.0

              Mandi_Name  District   State  ... Avg_Humidity  Sensor_Count  \
0        Hyderabad Mandi  Ludhiana  Punjab  ...     62.97561          36.0
1       Vijayawada Mandi  Ludhiana  Punjab  ...     62.97561          36.0
2   Khandwa Grain Market  Ludhiana  Punjab  ...     62.97561          36.0
3   Khandwa Grain Market  Ludhiana  Punjab  ...     62.97561          36.0
4  Bhilwara Grain Market  Amritsar  Punjab  ...     62.97561          36.0

   Price_Crash  Total_Arrivals_Qtl  Farmer_Count  Arrival_Records  \
0        False                 NaN           NaN              NaN
1        False                 NaN           NaN              NaN
2        False                 NaN           NaN              NaN
3         True                 NaN           NaN              NaN
4        False                 NaN           NaN              NaN

   Price_Risk_Score  Supply_Pressure_Score  Transport_Risk_Score  \
0         76.547842              81.739771             69.360902
1         88.713846              76.751158             71.490148
2         98.076923              78.908132             81.906196
3         98.076923              78.908132             81.906196
4         83.997754              82.662773             73.575557

   Priority_Score
0       76.668033
1       81.680300
2       89.092140
3       89.092140
4       81.512820

[5 rows x 24 columns]

In [86]:
# Save the final Power BI dataset
powerbi_data.to_csv(
    "powerbi_mandi_optimizer.csv",
    index=False
)

# Show exactly where the file was saved
import os

print("File saved successfully!")
print("Location:", os.path.abspath("powerbi_mandi_optimizer.csv"))

File saved successfully!
Location: c:\Users\Manya\Downloads\track3_agritech_dataset_files\powerbi_mandi_optimizer.csv

In [87]:
def assign_priority(score):
    if score >= 80:
        return "Critical"
    elif score >= 60:
        return "High"
    elif score >= 40:
        return "Medium"
    else:
        return "Low"


mandi_risk_final["Priority_Level"] = (
    mandi_risk_final["Priority_Score"]
    .apply(assign_priority)
)

print(
    mandi_risk_final[
        ["Mandi_ID", "Mandi_Name", "Priority_Score", "Priority_Level"]
    ]
    .sort_values("Priority_Score", ascending=False)
    .head(15)
)

    Mandi_ID                 Mandi_Name  Priority_Score Priority_Level
4   MANDI047                Orai Market       90.378665       Critical
1   MANDI004       Khandwa Grain Market       89.092140       Critical
0   MANDI044                Dehri Mandi       89.004744       Critical
3   MANDI041       Gurgaon Grain Market       87.929910       Critical
5   MANDI035             Guntakal Mandi       87.651174       Critical
9   MANDI011                Arrah Mandi       87.506416       Critical
2   MANDI027                 Kochi APMC       87.314526       Critical
7   MANDI050                Durg Market       86.891795       Critical
10  MANDI033  South Dumdum Grain Market       86.168954       Critical
15  MANDI025              Dindigul APMC       86.161495       Critical
16  MANDI022                 Eluru APMC       85.722786       Critical
6   MANDI046           Baranagar Market       85.589847       Critical
14  MANDI014      Bathinda Grain Market       84.933555       Critical
8   MANDI038            Jalandhar Mandi       82.951048       Critical
11  MANDI056             Bilaspur Mandi       82.898449       Critical

In [88]:
print(
    mandi_risk_final["Priority_Level"]
    .value_counts()
    .sort_index()
)

Priority_Level
Critical    27
High        30
Name: count, dtype: int64

In [89]:
# Rank mandis from highest to lowest Priority Score
mandi_risk_final["Priority_Rank"] = (
    mandi_risk_final["Priority_Score"]
    .rank(method="first", ascending=False)
    .astype(int)
)

# Assign priority based on rank
def assign_priority_rank(rank):
    if rank <= 10:
        return "Critical"
    elif rank <= 25:
        return "High"
    elif rank <= 42:
        return "Medium"
    else:
        return "Low"

mandi_risk_final["Priority_Level"] = (
    mandi_risk_final["Priority_Rank"]
    .apply(assign_priority_rank)
)

print(
    mandi_risk_final[
        [
            "Mandi_ID",
            "Mandi_Name",
            "Priority_Score",
            "Priority_Rank",
            "Priority_Level"
        ]
    ]
    .sort_values("Priority_Rank")
    .head(20)
)

    Mandi_ID                 Mandi_Name  Priority_Score  Priority_Rank  \
4   MANDI047                Orai Market       90.378665              1
1   MANDI004       Khandwa Grain Market       89.092140              2
0   MANDI044                Dehri Mandi       89.004744              3
3   MANDI041       Gurgaon Grain Market       87.929910              4
5   MANDI035             Guntakal Mandi       87.651174              5
9   MANDI011                Arrah Mandi       87.506416              6
2   MANDI027                 Kochi APMC       87.314526              7
7   MANDI050                Durg Market       86.891795              8
10  MANDI033  South Dumdum Grain Market       86.168954              9
15  MANDI025              Dindigul APMC       86.161495             10
16  MANDI022                 Eluru APMC       85.722786             11
6   MANDI046           Baranagar Market       85.589847             12
14  MANDI014      Bathinda Grain Market       84.933555             13
8   MANDI038            Jalandhar Mandi       82.951048             14
11  MANDI056             Bilaspur Mandi       82.898449             15
12  MANDI019    Karimnagar Grain Market       82.487990             16
21  MANDI017            Parbhani Market       82.336502             17
23  MANDI055            Chandigarh APMC       81.701347             18
41  MANDI051            Gulbarga Market       81.683327             19
17  MANDI003           Vijayawada Mandi       81.680300             20

   Priority_Level
4        Critical
1        Critical
0        Critical
3        Critical
5        Critical
9        Critical
2        Critical
7        Critical
10       Critical
15       Critical
16           High
6            High
14           High
8            High
11           High
12           High
21           High
23           High
41           High
17           High

In [90]:
def generate_reason(row):
    reasons = []

    if row["Price_Risk_Score"] >= 70:
        reasons.append("High price risk")

    if row["Supply_Pressure_Score"] >= 70:
        reasons.append("High supply pressure")

    if row["Transport_Risk_Score"] >= 70:
        reasons.append("High transport risk")

    if not reasons:
        reasons.append("Moderate combined risk")

    return " + ".join(reasons)


mandi_risk_final["Recommendation_Reason"] = (
    mandi_risk_final.apply(generate_reason, axis=1)
)

print(
    mandi_risk_final[
        [
            "Mandi_ID",
            "Mandi_Name",
            "Priority_Level",
            "Priority_Score",
            "Recommendation_Reason"
        ]
    ]
    .sort_values("Priority_Score", ascending=False)
    .head(15)
)

    Mandi_ID                 Mandi_Name Priority_Level  Priority_Score  \
4   MANDI047                Orai Market       Critical       90.378665
1   MANDI004       Khandwa Grain Market       Critical       89.092140
0   MANDI044                Dehri Mandi       Critical       89.004744
3   MANDI041       Gurgaon Grain Market       Critical       87.929910
5   MANDI035             Guntakal Mandi       Critical       87.651174
9   MANDI011                Arrah Mandi       Critical       87.506416
2   MANDI027                 Kochi APMC       Critical       87.314526
7   MANDI050                Durg Market       Critical       86.891795
10  MANDI033  South Dumdum Grain Market       Critical       86.168954
15  MANDI025              Dindigul APMC       Critical       86.161495
16  MANDI022                 Eluru APMC           High       85.722786
6   MANDI046           Baranagar Market           High       85.589847
14  MANDI014      Bathinda Grain Market           High       84.933555
8   MANDI038            Jalandhar Mandi           High       82.951048
11  MANDI056             Bilaspur Mandi           High       82.898449

                                Recommendation_Reason
4   High price risk + High supply pressure + High ...
1   High price risk + High supply pressure + High ...
0              High price risk + High supply pressure
3   High price risk + High supply pressure + High ...
5   High price risk + High supply pressure + High ...
9   High price risk + High supply pressure + High ...
2   High price risk + High supply pressure + High ...
7   High price risk + High supply pressure + High ...
10  High price risk + High supply pressure + High ...
15  High price risk + High supply pressure + High ...
16  High price risk + High supply pressure + High ...
6               High price risk + High transport risk
14              High price risk + High transport risk
8              High price risk + High supply pressure
11  High price risk + High supply pressure + High ...

In [91]:
def generate_action(row):
    actions = []

    if row["Price_Risk_Score"] >= 70:
        actions.append("Monitor price and MSP risk")

    if row["Supply_Pressure_Score"] >= 70:
        actions.append("Prioritize supply movement")

    if row["Transport_Risk_Score"] >= 70:
        actions.append("Prioritize transport")

    if not actions:
        actions.append("Continue routine monitoring")

    return " + ".join(actions)


mandi_risk_final["Recommended_Action"] = (
    mandi_risk_final.apply(generate_action, axis=1)
)

print(
    mandi_risk_final[
        [
            "Mandi_ID",
            "Mandi_Name",
            "Priority_Level",
            "Priority_Score",
            "Recommendation_Reason",
            "Recommended_Action"
        ]
    ]
    .sort_values("Priority_Score", ascending=False)
    .head(15)
)

    Mandi_ID                 Mandi_Name Priority_Level  Priority_Score  \
4   MANDI047                Orai Market       Critical       90.378665
1   MANDI004       Khandwa Grain Market       Critical       89.092140
0   MANDI044                Dehri Mandi       Critical       89.004744
3   MANDI041       Gurgaon Grain Market       Critical       87.929910
5   MANDI035             Guntakal Mandi       Critical       87.651174
9   MANDI011                Arrah Mandi       Critical       87.506416
2   MANDI027                 Kochi APMC       Critical       87.314526
7   MANDI050                Durg Market       Critical       86.891795
10  MANDI033  South Dumdum Grain Market       Critical       86.168954
15  MANDI025              Dindigul APMC       Critical       86.161495
16  MANDI022                 Eluru APMC           High       85.722786
6   MANDI046           Baranagar Market           High       85.589847
14  MANDI014      Bathinda Grain Market           High       84.933555
8   MANDI038            Jalandhar Mandi           High       82.951048
11  MANDI056             Bilaspur Mandi           High       82.898449

                                Recommendation_Reason  \
4   High price risk + High supply pressure + High ...
1   High price risk + High supply pressure + High ...
0              High price risk + High supply pressure
3   High price risk + High supply pressure + High ...
5   High price risk + High supply pressure + High ...
9   High price risk + High supply pressure + High ...
2   High price risk + High supply pressure + High ...
7   High price risk + High supply pressure + High ...
10  High price risk + High supply pressure + High ...
15  High price risk + High supply pressure + High ...
16  High price risk + High supply pressure + High ...
6               High price risk + High transport risk
14              High price risk + High transport risk
8              High price risk + High supply pressure
11  High price risk + High supply pressure + High ...

                                   Recommended_Action
4   Monitor price and MSP risk + Prioritize supply...
1   Monitor price and MSP risk + Prioritize supply...
0   Monitor price and MSP risk + Prioritize supply...
3   Monitor price and MSP risk + Prioritize supply...
5   Monitor price and MSP risk + Prioritize supply...
9   Monitor price and MSP risk + Prioritize supply...
2   Monitor price and MSP risk + Prioritize supply...
7   Monitor price and MSP risk + Prioritize supply...
10  Monitor price and MSP risk + Prioritize supply...
15  Monitor price and MSP risk + Prioritize supply...
16  Monitor price and MSP risk + Prioritize supply...
6   Monitor price and MSP risk + Prioritize transport
14  Monitor price and MSP risk + Prioritize transport
8   Monitor price and MSP risk + Prioritize supply...
11  Monitor price and MSP risk + Prioritize supply...

In [92]:
optimizer_output = mandi_risk_final[
    [
        "Mandi_ID",
        "Mandi_Name",
        "Price_Risk_Score",
        "Supply_Pressure_Score",
        "Transport_Risk_Score",
        "Priority_Score",
        "Priority_Rank",
        "Priority_Level",
        "Recommendation_Reason",
        "Recommended_Action"
    ]
].sort_values("Priority_Rank")

optimizer_output.to_csv(
    "mandi_optimizer_results.csv",
    index=False
)

print("Optimizer results saved successfully!")
print("Shape:", optimizer_output.shape)
print(optimizer_output.head(10))

Optimizer results saved successfully!
Shape: (57, 10)
    Mandi_ID                 Mandi_Name  Price_Risk_Score  \
4   MANDI047                Orai Market         88.009768
1   MANDI004       Khandwa Grain Market         98.076923
0   MANDI044                Dehri Mandi         95.554210
3   MANDI041       Gurgaon Grain Market         89.289564
5   MANDI035             Guntakal Mandi         87.937570
9   MANDI011                Arrah Mandi         78.071183
2   MANDI027                 Kochi APMC         94.301192
7   MANDI050                Durg Market         84.035309
10  MANDI033  South Dumdum Grain Market         88.246991
15  MANDI025              Dindigul APMC         83.138054

    Supply_Pressure_Score  Transport_Risk_Score  Priority_Score  \
4               89.474628             97.656961       90.378665
1               78.908132             81.906196       89.092140
0               91.179107             69.369534       89.004744
3               88.122064             84.242543       87.929910
5               89.411179             84.295175       87.651174
9              100.000000             92.354125       87.506416
2               80.897036             79.474097       87.314526
7               92.042980             86.306235       86.891795
10              82.294384             86.785714       86.168954
15              86.693509             92.922078       86.161495

    Priority_Rank Priority_Level  \
4               1       Critical
1               2       Critical
0               3       Critical
3               4       Critical
5               5       Critical
9               6       Critical
2               7       Critical
7               8       Critical
10              9       Critical
15             10       Critical

                                Recommendation_Reason  \
4   High price risk + High supply pressure + High ...
1   High price risk + High supply pressure + High ...
0              High price risk + High supply pressure
3   High price risk + High supply pressure + High ...
5   High price risk + High supply pressure + High ...
9   High price risk + High supply pressure + High ...
2   High price risk + High supply pressure + High ...
7   High price risk + High supply pressure + High ...
10  High price risk + High supply pressure + High ...
15  High price risk + High supply pressure + High ...

                                   Recommended_Action
4   Monitor price and MSP risk + Prioritize supply...
1   Monitor price and MSP risk + Prioritize supply...
0   Monitor price and MSP risk + Prioritize supply...
3   Monitor price and MSP risk + Prioritize supply...
5   Monitor price and MSP risk + Prioritize supply...
9   Monitor price and MSP risk + Prioritize supply...
2   Monitor price and MSP risk + Prioritize supply...
7   Monitor price and MSP risk + Prioritize supply...
10  Monitor price and MSP risk + Prioritize supply...
15  Monitor price and MSP risk + Prioritize supply...